### ISSUE TITLE
Cannot Access Images That Aren't in Subfolders

### ISSUE THREAD

**Issue by IronSheepdog** [VorlonCD/bi-aidetection#1]
Most Blue Iris setups have all of the AI alert images dumped into one universal folder, rather than multiple subfolders (one for each camera). It seems as if I am having a problem now that each camera has it's own input folder location to choose. I do specify the AI alert image input folder under the Settings tab. However, if I do not specify an input folder under each camera, it acts as if no images are being found. If I do specify the universal input folder under each camera, I see the following error in the log:

> Error: Could not match combobox dropdown '' to a known camera name?

Note: AI Tool is installed on the same computer as Blue Iris. Deep Stack is installed on an Ubuntu machine and accessed over the network. Everything worked fine with the original version of AI Tool 1.67.

**Comment by VorlonCD** [comment]
I believe fixed in the latest release.   If not, stop any AITOOL service you may have running, and then make sure each camera path is empty and make sure on settings, the Monitor subfolders checkbox is enabled IF there are subfolders for each camera.  Are your BI folders on a network path or on a NAS?   The filewatcher may have issues detecting changes from some types of file storage.   If still have issues, send me log entries referencing 'UpdateWatchers'.
https://github.com/VorlonCD/bi-aidetection/releases

**Comment by IronSheepdog** [comment]
Yes the latest version fixed it. Thanks!!

Lucas Bingman
lcbingman@gmail.com
