### ISSUE TITLE
Awesome! Just a question about the service and desktop tool - 2 instances running?

### ISSUE THREAD

**Issue by Yonny24** [VorlonCD/bi-aidetection#100]
Just upgraded the AI tool and a vast improvement thanks for the hard work.

Now I had the original AI tool installed as a windows service also.
After upgrading the desktop tool to your fork do I need to uninstall the windows service and reinstall it? I was getting errors of 2 instances running.

Does the AI desktop tool start up on boot or is this the purpose of running it as a service and only opening the desktop tool to adjust settings and then closing it?

Thanks again

**Comment by Yonny24** [comment]
Just the windows service running - seemed to have picked up and processed all of my images which is good. So I'm assuming I just use the tool for setting adjustments.

**Comment by sethfeinberg** [comment]
I have the same issue with everything seemingly working fine (better even!! Thanks!!) but getting the "2 instances running" error.  Did you solve it by uninstalling the service and reinstalling? Would you mind sharing that process to a n00b?

**Comment by lapnesee** [comment]
Hi guys, we need to open the task manager and kill AItools.exe. good day !

**Comment by sethfeinberg** [comment]
Thanks! Every time? Or just once then reopen?

**Comment by lapnesee** [comment]
After each restart of windows, it is useful in the event of a crash.

**Comment by lapnesee** [comment]
Once minimized he puts himself at the end of the task bar

**Comment by VorlonCD** [comment]
If you need to open the GUI to view anything or change settings you must first STOP the service.    Then close the GUI app and re-start the service.  They should not be running at the same time, thats why you get the error.    And even if it worked in the past it should not have been done since it could cause corrupt settings.

If using a service, do not enable Settings > Start with user login.

You shouldnt have to re-create the old service as long as the path to AITOOL.EXE is the same.

Once and a while I see a case where AITOOL.EXE doesnt show up in Task Manager but it IS running.   In that case, need to either reboot or use a tool like PROCESS EXPLORER or PROCESS HACKER (v3 beta) to find it in memory and kill it.

As an alternative to using the service:  (which I use)
1) Enable Start at user login
2) Google for how to automatically log in on windows start - your username/password gets stored somewhere in the registry.

**Comment by sethfeinberg** [comment]
Ahh many thanks I will give this alternative a shot

**Comment by Yonny24** [comment]
Awesome thanks. After playing around with it yes realized that you had to stop the service then open the tool to adjust settings.

**Comment by Yonny24** [comment]
The static mask option is great!!

**Comment by sethfeinberg** [comment]
> If you need to open the GUI to view anything or change settings you must first STOP the service. Then close the GUI app and re-start the service. They should not be running at the same time, thats why you get the error. And even if it worked in the past it should not have been done since it could cause corrupt settings.
> 
> If using a service, do not enable Settings > Start with user login.
> 
> You shouldnt have to re-create the old service as long as the path to AITOOL.EXE is the same.
> 
> Once and a while I see a case where AITOOL.EXE doesnt show up in Task Manager but it IS running. In that case, need to either reboot or use a tool like PROCESS EXPLORER or PROCESS HACKER (v3 beta) to find it in memory and kill it.
> 
> As an alternative to using the service: (which I use)
> 
> 1. Enable Start at user login
> 2. Google for how to automatically log in on windows start - your username/password gets stored somewhere in the registry.

Just wanted to report back that I finally got around to enacting this method and it went well, thank you! Only snag was that the option for auto logon simply wasn't present in the settings or the registry as stated in multiple how-to's I found in the internet. I believe maybe related to the hardware or windows version. In the end, I needed to add a registry entry from the CMD and the option showed up in settings.

**Comment by VorlonCD** [comment]
Yeah NETPLWIZ.EXE used to work but not in new win10 versions.   This is the registry entry for auto login:
https://docs.microsoft.com/en-us/troubleshoot/windows-server/user-profiles-and-logon/turn-on-automatic-logon
