### ISSUE TITLE
Error sending image to Telegram

### ISSUE THREAD

**Issue by ytwytw** [VorlonCD/bi-aidetection#121]
![image](https://user-images.githubusercontent.com/2984062/103189090-171e7400-4899-11eb-8379-5bef3ee4a793.png)

Any idea?

MQTT or Other http error messages are coming fine, but not the image. 

![image](https://user-images.githubusercontent.com/2984062/103189130-3f0dd780-4899-11eb-86ed-f308bd3c2751.png)

also the error message in the log is not quite descriptive, is it possible to improve a bit more?

I have already have set cooldown time to 5min, assuming its not related spamming

**Comment by xdreamwalker** [comment]
I have been seeing this for some time in many versions:
![image](https://user-images.githubusercontent.com/24192512/104140837-7d1ef700-5381-11eb-9c26-a2442cef2c75.png)
![image](https://user-images.githubusercontent.com/24192512/104140852-90ca5d80-5381-11eb-97ef-32854631e6df.png)
The log shows and error and the error counter goes up. when a notification to Telegram or Pushover is skipped due to detected object "not in trigger objects list."
Thankfully those 'errors' do not get sent to Telegram/Pushover as errors.
Is it possible to have those not marked as errors?

**Comment by VorlonCD** [comment]
This fixes the Error Sending error when it simply fails to match an object on the list.

I dont know about the MQTT issue, but try the latest and send me log entries from before the actual error if still happening.

[AITool-VorlonCD-v2.0.521.zip](https://github.com/VorlonCD/bi-aidetection/files/5793678/AITool-VorlonCD-v2.0.521.zip)

**Comment by xdreamwalker** [comment]
That's done the trick for my issue. Thanks!

**Comment by ytwytw** [comment]
Tried the version above, it still does not work, but no more error messages. weird.
I tried chat id with and without - sign, no difference.
could it be something on telegram side?

**Comment by ytwytw** [comment]
![image](https://user-images.githubusercontent.com/2984062/104869711-ac4ede80-5914-11eb-8564-c30ddbd24020.png)
 it appears sending error message to telegram works, but not alert

**Comment by ktran-1** [comment]
is there a way to send like a 5-10 second gif with telegram, i see there is a different bot that uses ffmpeg but i would like to do it from this
