### ISSUE TITLE
Add Schedule feature for each Specific Object?

### ISSUE THREAD

**Issue by wowueh** [VorlonCD/bi-aidetection#124]
Would you please add feature to schedule for each type of object-detection. For example: detect car in the morning, detect person at night ...etc
By the way, Does Aitool has ability to request face detection?

**Comment by VorlonCD** [comment]
I havent done the per-object schedule feature because I want it to be part of a larger change in the way actions are handled.

But you CAN schedule telegram and pushover notifications to certain time of the day already.

But yes, AITOOL now supports FACE it in 2 ways:

1) Add either AWS Rekognition or SightHound Person detection as a "Refinement server".   Those external tools give you 5000 free images a month so AITOOL will only ask those external services for details if the local Deepstack already found a "person".  You have to sign up for the service to get the API key.  And in the case of AWS it requires credit card to sign up:
![image](https://user-images.githubusercontent.com/7512113/107892824-98879f80-6ef5-11eb-8526-bdf82f1d906a.png)

I dont know if those services let you train custom faces or not, but they DO provide some cool (and scary) info:

![image](https://user-images.githubusercontent.com/7512113/107892911-1186f700-6ef6-11eb-9294-1c5f6a0fc1d1.png)

2) Read up on deepstack face training and detection, then add DEEPSTACK FACES as a "Linked" server in AITOOL.    Your primary server will still be the regular deepstack server, but you "link" it to FACES so that the results are combined.   Note it is not very useful unless you "train it".   It just says here is a FACE otherwise.

![image](https://user-images.githubusercontent.com/7512113/107892788-5eb69900-6ef5-11eb-9162-8dd4bd05dbca.png)

Latest version:
https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip

**Comment by VorlonCD** [comment]
@wowueh - Done and done  (For everything except SOUND and URL TRIGGER options anyway):

[AITool-VorlonCD-v2.0.845.zip](https://github.com/VorlonCD/bi-aidetection/files/6071586/AITool-VorlonCD-v2.0.845.zip)

![image](https://user-images.githubusercontent.com/7512113/109710471-b3037f00-7b6b-11eb-9e84-e709b5dfdb1e.png)
