### ISSUE TITLE
Static Mask Issue

### ISSUE THREAD

**Issue by DM-AU** [VorlonCD/bi-aidetection#132]
Hi again,

I am having an issue, which may not be an issue with AI Tool directly. It is to do with a static mask i have set on an image, I am getting the following errors:

The resolution of the mask 'C:\AI Tool\_Settings\Driveway.bmp' does not equal the resolution of the processed image. Skipping privacy mask feature. Image: 856x480, Mask: 3840x2160

Masking error? 'Driveway' ('Car') - DynMaskResult=Unknown, ImgMaskResult=Error

The background is Blue Iris camera is 4k with substream is sending motion snapshot every 3 seconds and a static mask in AI Tool to block results from the road. However I do not know if its my configuration or just the way it is but Blue Iris does send either a snapshot of the substream OR the 4k image (i dont know the logic behind this - it might be the first snap is low res and the next is high res).

![image](https://user-images.githubusercontent.com/66342521/103709504-c6301d80-5006-11eb-83ae-2eab2999e425.png)

Do you know if this is a Blue Iris config issue or something that can be tweaked in AI Tool?

Thanks
David

**Comment by balucanb** [comment]
Same issue here @VorlonCD, I have been running into it for the last 3 releases. Currently running 2.0.526 and the deepstack v2 beta (CPU). I have tried to restrict the size of the snapshot in BI, manually changed the size of the mask using PS, deleted all the masks out of the settings folder, repeatedly cleared the masks and re-drew them (in AI-Tool), tried to just use static mask option in the dynamic mask settings. but nothing works. it just seems to ignore it all. Also as I mentioned in a previous issue post when I go into draw the mask the  snapshot is still changing size on me, pic takes up the whole screen, draw the mask, sometimes when I release the mouse the pic will resize to about 25% click save go back in and the mask now does not match the pic, or save it all looks good then I go back in later and the pic has either gotten bigger or smaller and then the mask of course does not match, also just today I went into the current camera that is throwing this error, the mask is way off, I tried to draw on that mask to see if the pic size was going to change and whether I used the brush or rectangle as soon as I release the mouse the area I just drew disappears? Sorry this was so long just trying to be descriptive man, Still love everything you and the other folks are doing on this! I can post pics if you need just let me know.

**Comment by VorlonCD** [comment]
This fixes a bug where the CUSTOM MASKING editor would not always use the mask file you assign in CAMERA settings.   This would only have been a problem if the mask file name did not match the AITOOL camera name.

[AITool-VorlonCD-v2.0.534.zip](https://github.com/VorlonCD/bi-aidetection/files/5809305/AITool-VorlonCD-v2.0.534.zip)

If you make **any** changes to the BI image size or steam being used, you wil need to recreate the mask again:

1.  Verify the filename in the TITLE of the custom masking dialog matches the name you have set for "Custom mask file" in Camera settings
2. Make sure at least **one new image** has been processed by AITOOL after the camera change (Since this is the template file used when creating the new mask)
2. In CUSTOM MASKING, hit CLEAR
3. Make the new mask and save.

**Comment by balucanb** [comment]
I have done everything you said @VorlonCD  still not working for me. still getting the mis-match size error? I have deleted everything mask related, cleared out the monitoring files, re-installed, etc. I can not get it to work.

**Comment by VorlonCD** [comment]
Have you tried updating BI?   Maybe there is something going on where it doesn't constantly send the same resolution file?

Perhaps your camera automatically reduces resolution when the signal quality is bad?  I would double check settings directly in the cameras web GUI and make sure the default stream settings are correct.

You can prove if BI is sending varied resolutions by browsing to the alerts folder and enabling the WIDTH and HEIGHT columns.  This will let you quickly scan through to see if any are different.   **I'm almost sure that is the going to be the case.**

I recently had a camera that forgot what its default stream settings where and I see exactly that in my output folder - Some 720x1280 and some 1080x1920.

If they are different, you will have to take it up with your camera manufacturer or Blue Iris support.  I dont really know what I could do on this end

Otherwise, if they are all the same, I'll need:

- Screenshots of camera settings and inside the custom masking dialog
- Screenshots of BI Video and record tabs in camera properties.
- Pick a recent image from history tab that failed, right-click > Locate in log, then send me the log entries.

**Comment by balucanb** [comment]
Cool beans, I will check that. It has to be the only thing I have not checked! BI is up to date and I have really good WiFi signals to all the cameras. this all started around the time multiple DS address' and pushover options were added. Never had any issues prior (with the cameras) so my bet is I am hosing something up. Plus now that I think about it I did a fresh WIN 10 install so chances are good when I re installed BI I may have missed something.

**Comment by DM-AU** [comment]
Yes my issue is with Blue Iris outputting different resolutions. I have contacted their support for assistance. 

Would you know from my screenshot above what would need changing to get a consistent output?

**Comment by VorlonCD** [comment]
Probably a setting on video tab in bi causing it

**Comment by DM-AU** [comment]
![image](https://user-images.githubusercontent.com/66342521/104530674-96b18e80-5660-11eb-8100-83819ae8508d.png)
![image](https://user-images.githubusercontent.com/66342521/104530703-a630d780-5660-11eb-8f73-75454cb91727.png)

Help narrow it down?

**Comment by balucanb** [comment]
maybe BI is my issue also then..I have restricted the size in BI like in your screenshot and I have removed it, even tried to restrict it in BI and then use photoshop to match the size of the mask but it still throws errors.

**Comment by VorlonCD** [comment]
Maybe BI cant keep a lock on the stream and reverts to substream or something like that?   Or the camera itself changes the stream based on signal quality?   Note that I have a camera constantly downgrading the bitrate (not dimensions) because it thinks the signal quality is bad.  EVEN though my router says there is a strong wifi signal to that device.   Thats why I have most of mine hard-wired.

I think in the Blue Iris STATUS window you can look at the PIXELS column to keep an eye on the stream size.  From the manual:

"CAMERA STATUS WINDOW Here you will find an overview of your cameras and their current operation.  There are also a number of metrics important for optimizing performance.Pixels This is the number of picture elements in each image—**the width multiplied by the height**.  The value is given in MP (megapixels or millions of pixels). "

**Comment by balucanb** [comment]
I will have to check that out. Maybe it is unrelated but last night I went in to all the cameras and just unchecked the Dynamic masking option, you can still draw a mask on the image so I figured WTH, the errors stopped but it is ignoring the mask I drew, maybe it is supposed to work that way, not sure but obviously did not fix my problem based on the numerous alerts on my car in the driveway, Unrelated but I am running the latest CPU windows beta of Deepstack and that SOB is erroring out also! Already noted it on that thread waiting on a response from John. I think I may do the nuclear option, clean install windows, drop back 4 or 5 version on AI-Tool and go to the pre-beta version of DS then ever so slowly move forward and really pay attention to what is going on. Maybe I will try to go DOCKER again? Nah probably not since I don't have a box I can take advantage of GPU. No advantage or?

**Comment by DM-AU** [comment]
> Maybe BI cant keep a lock on the stream and reverts to substream or something like that? Or the camera itself changes the stream based on signal quality? Note that I have a camera constantly downgrading the bitrate (not dimensions) because it thinks the signal quality is bad. EVEN though my router says there is a strong wifi signal to that device. Thats why I have most of mine hard-wired.
> 
> I think in the Blue Iris STATUS window you can look at the PIXELS column to keep an eye on the stream size. From the manual:
> 
> "CAMERA STATUS WINDOW Here you will find an overview of your cameras and their current operation. There are also a number of metrics important for optimizing performance.Pixels This is the number of picture elements in each image—**the width multiplied by the height**. The value is given in MP (megapixels or millions of pixels). "

The cameras are Annke C800 which are all hardwired to gigabit POE switch. From the image below you can see the bitrate changes a bit between cameras:
![image](https://user-images.githubusercontent.com/66342521/104659877-945f3b00-5719-11eb-854c-50a88f6e45f3.png)
These are the settings on the camera, which show variable bitrate enabled:
![image](https://user-images.githubusercontent.com/66342521/104660014-e011e480-5719-11eb-8953-1472fa47b860.png)

Anything jumping out?
From memory when i read the manual Blue Iris uses the sub stream for motion detection to avoid encoding the higher stream. I wonder if this isnt working properly. Ie, it uses the substream initially for motion and then after a few seconds of motion it switches to the higher stream. This kinda makes sense as right now we are having a lot of wind and constant motion snapshots are being triggered, the majority of which are in high res.

**Comment by VorlonCD** [comment]
@DM-AU  - I really have no idea what would cause it.  It might not hurt to delete/recreate the camera in BI.

I might be able to work something out where I try to read a mask BMP file with the resolution attached to the filename like CAM1_WIDTH_HEIGHT.BMP, so you can create a separate mask for each resolution given to you.   But I still think this really needs to be fixed in the BI side.

@balucanb - For deepstack windows beta crashing out, pop in my customized copy of **detection.py** that is found here:
https://github.com/johnolafenwa/DeepStack/issues/51#issuecomment-756788251

Then, the next time it crashes, the error log may provide an actual error rather than the 'File Not Found':
C:\Users\username\AppData\Local\DeepStack\logs\stderr.txt

Otherwise, if you cant take advantage of the GPU windows version, I would go back to the latest DOCKER beta.

**Comment by balucanb** [comment]
So progress is being made! Replaced the file and so far so good that error with DS seems to be good now Thanks! My AI-tool log errors seem to have cleared up, I reenabled the dynamic option on 1 camera and so far it is behaving, There has also bee a couple BI updates pushed out Only thing I am getting now is this- 
A task was canceled. [TaskCanceledException] Mod: <GetDetectionsFromAIServer>d__46 Line:1565:21 
Is this a trigger error or a missing trigger error?

**Comment by Tinbum1** [comment]
> 

> A task was canceled. [TaskCanceledException] Mod: d__46 Line:1565:21 

I got this error a lot yesterday when it was raining and I was pushing loads of images to DeepStack.

**Comment by VorlonCD** [comment]
@balucanb - what is the function name that is happening in?   Usually Task Canceled means that the HTTP connection failed to respond / timed out after 55 seconds (configured via **HTTPClientTimeoutSeconds** in the aitool.settings.JSON file)
Any new errors in stderr.txt, or was it just a one off where deepstack just happened to be extra slow?

**Comment by balucanb** [comment]
Not going to pretend I know what it is you are asking me but I assume you are asking what is in the txt log entries if not tell me and I will get it posted, I copied all the entries before and up to the error in the attached, I can post the whole log just thought this might be quicker for you. Ref the stderr.txt I think your file fixed that, let it run all night and it is still humming along with no issues, we will see what happens today,,,

[aitool error.txt](https://github.com/VorlonCD/bi-aidetection/files/5820966/aitool.error.txt)

**Comment by VorlonCD** [comment]
So yes the error was in the DETECTOBJECTS function, so the Task Canceled simply means that Deepstack server did not respond to the request in 55 seconds.  Which usually means it crashed or VERY busy since responses are usually less than a second.    

After the crash (but before you try to re-start it), capture the contents of this file:
C:\Users\username\AppData\Local\DeepStack\logs\stderr.txt

It will not exist or be empty if you have already re-started deepstack.

**Comment by balucanb** [comment]
so this is what I did. I cleaned all the snapshots out of my AI folder, deleted the log file, restarted the computer, started BI and AI tool and checked if the Deepstack tab said "running" (it did) then went to the log tab and waited... as soon as it threw the error I checked the stderr.txt on the deepstack tab, nothing. I then went to the actual file location- file is there but 0 data, there is another file in there also called stdout, ( no clue if that helps but I attached it with the log) waited for a 2nd error to pop up
 then saved the error log.

[stdout.txt](https://github.com/VorlonCD/bi-aidetection/files/5822730/stdout.txt)
[AITool.[2021-01-15].log](https://github.com/VorlonCD/bi-aidetection/files/5822732/AITool.2021-01-15.log)

**Comment by VorlonCD** [comment]
Let me know how this new version works.    Mask BMP files now are automatically renamed as filename**WidthxHeight**.bmp and the Draw Custom mask lets you scan your image folder for all known resolutions for the snapshots, then create a mask for each resolution you might encounter.

@balucanb - if you keep seeing random the task canceled, edit the deepstack URL and increase the new TIMEOUT setting.   However, if all deepstack calls start failing, look again for stderr.txt and stop/start Deepstack.  Or use the Docker version as it seems to be more stable than Windows.   Or run fewer instances/ports.

[AITool-VorlonCD-v2.0.569.zip](https://github.com/VorlonCD/bi-aidetection/files/5826993/AITool-VorlonCD-v2.0.569.zip)

**Comment by balucanb** [comment]
Thanks, Just FYI I have done no changes since I posted the above and the errors have continued, still getting notifications and all that though. I will give your suggestions and the new build a try and let you know.

**Comment by DM-AU** [comment]
Thanks, i will try it now.
I am in conversation with Blue Iris trying to work out why it happens. They seem to think its to do with the key frames relation to the pre trigger record buffer but mine is set to 15 seconds. Will update on whether the AITool update fixes this and also what we find out with Blue Iris. Appreciate the help!

**Comment by balucanb** [comment]
@VorlonCD looking at the entries on the settings tab, AI server-2nd from the end the default URL is listed with port 80, I am not using that port, should it be showing the port I am using there? if so where can I change it? did not see it in the settings file. I see the BI URL and the deepstack entries and ports but not he BI port

**Comment by balucanb** [comment]
> Yes my issue is with Blue Iris outputting different resolutions. I have contacted their support for assistance.
> 
> Would you know from my screenshot above what would need changing to get a consistent output?

Here is what Ken told me from BI support- 
"If you are using dual-streaming, the AOI setting is used automatically for adjusting the size of the sub-stream to match the aspect ratio of the main stream.  Your camera must be sending a sub stream image with 432 lines.  This has always been the way the sub stream is supported."
I already knew this so I assume the issue (mine) may be the camera's themselves? Can't find any problems though, This has not always been a problem. I have checked it all again and again plus been making sure I update all pieces of the set up and trying the recommendations from VorlonCD , so I am at a loss on how to fix it.

**Comment by VorlonCD** [comment]
@balucanb - "DefaultURL" is just how it sounds.  It is the URL:port used when you FIRST add a new AI server.   That setting is only used as sort of a template, not after that so it doesnt matter.

I cant help you much more on the BlueIris side of things.   One thought - I recently had to go back to the "Last stable version" which was dated December to solve a few weird things happening in BI including crashing.

But in the AITOOL version I posted above, you should be able to create a mask for each resolution image.  This should avoid the "**Does not equal resolution**" error.   It doesnt work?  Or are you talking about a different error?

**Comment by balucanb** [comment]
@VorlonCD Tracking. The image size errors seem to have gone away and your "scan" feature seems to work great BTW. Lack of the resolution errors could have been one of your updates or maybe something I changed? My money is on you :) I keep all aspects of the set up up to date, just updated the camera FW, which should not have anything to do with this issue (I had some Reolinks falling off the network) Anyway the only thing I am getting now is time out error-

HTTPClient timeout at 65 seconds (Max=65 set in 'HTTPClientTimeoutSeconds' in aitool.settings.json): A task was canceled. [TaskCanceledException] Mod: <GetDetectionsFromAIServer>d__48 Line:1575

I changed it to 65 as you can see but still no love, I am getting fewer of them than before though. I can not find anything in the logs that give any indication of what is going on- Personally I am thinking it is on the Deepstack side. It is just annoying at this point, I still get notifications etc. How many am I missing is the question? Have not took the time to bounce the pics in the AI folder to what telegram is sending. I know if I would just go back to Docker it would most likely all be OK...Me and Docker have a love/hate thing going so I am trying to stay with the "esay" option of running the Win version. 👍  Thanks again

**Comment by DM-AU** [comment]
Just an update from me, the masking errors have been resolved by the update provided by VorlonCD. Obviously this doesnt fix the underlying issue as to why BI is outputting different sizes, but I dont think i really need to worry as this work around is sufficient.

Thanks so much @VorlonCD

**Comment by VorlonCD** [comment]
@balucanb - For the timeout errors...

- Does deepstack work for a while and then stop for GOOD with those timeout errors until you STOP/START in the deepstack tab?  Or are the timeout errors periodic?
- And each time it stops you confirm there is nothing new in STDERR.TXT as mentioned before?
- The timeout setting in the JSON file can be increased as high as you want.  Try setting to 300 seconds to see if deepstack EVER comes back.  In the log you should see maximum times listed for the AI server.  Look for huge numbers above 60000ms to see how long it is taking.   If simply taking longer than 60 seconds to respond in some cases but it does eventually come back, you might have a drive or memory going bad.
- When a single copy of deepstack is running you should see TWO copies of python.exe running for each deepstack.exe in Task Manager > Details tab.   If you dont find enough copies running that is why its not working.
- If you have a 3rd party antivirus product installed, especially if it has a Firewall component, **uninstall it** and reboot.   Windows should revert back to the out of the box antivirus and its usually just fine.   If this helps you will then know who the culprit was.
- Try temporally uninstalling all other versions of Python in your list of installed programs.   It should use the copy of python already in the deepstack folder.

**Comment by balucanb** [comment]
> @balucanb - For the timeout errors...
> 
> * Does deepstack work for a while and then stop for GOOD with those timeout errors until you STOP/START in the deepstack tab?  Or are the timeout errors periodic?
> * And each time it stops you confirm there is nothing new in STDERR.TXT as mentioned before?
> * The timeout setting in the JSON file can be increased as high as you want.  Try setting to 300 seconds to see if deepstack EVER comes back.  In the log you should see maximum times listed for the AI server.  Look for huge numbers above 60000ms to see how long it is taking.   If simply taking longer than 60 seconds to respond in some cases but it does eventually come back, you might have a drive or memory going bad.
> * When a single copy of deepstack is running you should see TWO copies of python.exe running for each deepstack.exe in Task Manager > Details tab.   If you dont find enough copies running that is why its not working.
> * If you have a 3rd party antivirus product installed, especially if it has a Firewall component, **uninstall it** and reboot.   Windows should revert back to the out of the box antivirus and its usually just fine.   If this helps you will then know who the culprit was.
> * Try temporally uninstalling all other versions of Python in your list of installed programs.   It should use the copy of python already in the deepstack folder.
> * **And reduce your port/instance count to ONE for a while to see if it is only when multiple instances are running**

@VorlonCD So sorry I forgot to reply to this- Deepstack does not appear to ever stop that I can see, the errors are periodic. It happens on all the cameras, not at once but it looks like once it starts it hits all of them. There is never any entries in the STDERR file. No anti virus issues. Tried the single instance, honestly I think it got worse when I did that, I still need to go check the possible python issues- must have missed that the first time I read this. Some good news, maybe. I had already adjusted the timeout period up to 65 but no real help. I went in earlier today and just pushed it to 120 I think it was. So far, so good no problems, I have the log up on a separate monitor and am watching it. If this works then that's good just hate to have to push it that high. My computer is not super but w/ a I7 and 32gb of ram I would think it would be OK. Still kinda think it is on the DS side myself. Yes I see that big elephant in the room named DOCKER... Trying to not go over there yet. LOL.

**Comment by VorlonCD** [comment]
@balucanb - I'm also getting about one timeout a day with the CPU version (running 2 copies).   I assume deepstack is buggy or else some kind of long running "garbage collection" or memory cleanup needs to happen periodically which causes it to take a long time to respond.

I cant really fix a periodic issue in ATOOL, but the next version will have a "Restart deepstack if xx failures in a row" option.  (It has been committed to github, i just cant make a new ZIP right now)

**Comment by balucanb** [comment]
I Let it run all night and woke up to 44 I think it was, IDK, it has to be DS. Ken  (Blue Iris) is in my computer as we speak trying to fix a issue with the latest update so if he finds anything that I think would somehow be causing it I will let you know. Highly unlikely they are connected though.

**Comment by VorlonCD** [comment]
Unless BlueIris and Deepstack are trying to share a port, BI should have nothing to do with this issue.   But the recent release of BI is the ONLY one in 2 years I've had to revert to stable version, so I'm sure he will be able to work it out shortly.  Ken on your computer is kind of like Jesus visiting your house.  Except I believe in Ken.  :)

**Comment by balucanb** [comment]
Yeah he was in there for a quick minute. No clue what he did, hoping he shoots me an email breaking it down. I do know it is now running the lastest update and she ain't crashing. 👍
