### ISSUE TITLE
  Deepstack returned 'Invalid value for min_confidence'

### ISSUE THREAD

**Issue by Mrdindon** [VorlonCD/bi-aidetection#136]
Whatever I put under the lower "confidence limits" other than 0% returns the following error:

AITool logs:
  Deepstack returned 'Invalid value for min_confidence' - http status code 'BadRequest' (400) in 8ms: Bad Request
... AI URL for 'DeepStack' failed '26' times.  Disabling: 'http://127.0.0.1:81/v1/vision/detection'

Deepstack logs:
[GIN] 2021/01/09 - 10:13:29 |←[90;43m 400 ←[0m|      5.4033ms |       127.0.0.1 |←[97;46m POST    ←[0m /v1/vision/detection

AI Tool version :2.0.476.7678
DeepStack : 2021.01 beta - CPU (tried with GPU version also)
Detection API - Medium.

I have no idea if the error is from AITool or Deepstack... any idea ?

**Comment by VorlonCD** [comment]
History tab > settings > Restrict at source will disable sending 'min_confidence' to deepstack with the request, but you shouldnt have to do that.  I've had that setting enabled for a while with threshold above 1.

Where are you setting the threshold?   In Camera settings or for the URL as an override?

Try another threshold value, maybe some values convert to a number that has too many decimal places for deepstack to handle

This is the deepstack code that returns the error in middlewares.go.  And I checked to make sure I was correctly converting, for example 45% to a decimal .45 before giving to deepstack.

`               nms := c.PostForm("min_confidence")

		if nms != "" {
			val, err := strconv.ParseFloat(nms, 32)

			if err != nil {

				response := response.ErrorResponse{Success: false, Error: "Invalid value for min_confidence"}

				c.JSON(400, response)
				c.Abort()

				return

			} else {

				if val > 1.0 {

					response := response.ErrorResponse{Success: false, Error: "min_confidence cannot be greater than 1"}

					c.JSON(400, response)
					c.Abort()
					return
				}

			}`

**Comment by Mrdindon** [comment]
So "Restrict Threshold at source" is enabled under History tab -> history settings
And I was trying with the following values under Camera tab -> Confidence limits -> lower : 60 or 65 or 70% while keeping Upper at 100%.

Not sure to understand what you mean by : "or the URL as an override"

deepstack command : C:\DeepStack\server\DeepStack.exe --VISION-DETECTION True --MODE Medium --PORT 81
URL : http://127.0.0.1:81/v1/vision/detection

Also if I check stderr.txt, the file is empty and when I run deepstack in debug mode (showing the console) I see no errors..

**Comment by Tinbum1** [comment]
![image](https://user-images.githubusercontent.com/66704787/104109279-27d0e000-52c4-11eb-8e93-70d17f0ec6bc.png)

**Comment by Mrdindon** [comment]
Thanks Tinbum1,
So I tested to put lower confidence back to 0% at the camera level and put it at 60% at the server level (based on your screenshot) but got the same results.
So I'm not sure if I get that wrong or not but I don't get that error anymore when I unchecking "restrict at source" from the history tab..

**Comment by balqosz** [comment]
Hi VorlonCD!

 Have you seen this? https://github.com/VorlonCD/bi-aidetection/issues/126#issuecomment-754941414

So reading this thread, if I set my min confidence to 0, also the problem of queue growing disappears! With the reverted code in that post, the problem disappears too. So min confidence or that code, or both, may be the problem. Can you check?

**Comment by VorlonCD** [comment]
So I've had "restrict at source" and min confidence set higher than 0 in the deepstack URL settings for a number of builds now and havent seen that error coming back from deepstack.   Try:

1. Clean out the AITOOL folder (except for _settings)
2. Download this and right-click > properties > UNBLOCK 
[AITool-VorlonCD-v2.0.526.zip](https://github.com/VorlonCD/bi-aidetection/files/5798600/AITool-VorlonCD-v2.0.526.zip)
3. Start fresh by removing all the DLL/EXE files from your AITOOL folder, then copying all the new ones in:
3. Unzip to same folder
4. Double check you have the latest Deepstack version: [Releases](https://github.com/johnolafenwa/DeepStack/releases)
5. If using the GPU version there is a slightly newer release [Here](https://forum.deepstack.cc/t/deepstack-windows-gpu-bug-fix/624?u=john)

If that doesnt help try copying in [my slightly updated copy of the deepstack detection.py file](https://github.com/johnolafenwa/DeepStack/issues/51#issuecomment-756788251) that helps stabilize a few issues. 

Also, try re-creating the camera in AITOOL.

**Comment by balqosz** [comment]
Hi VorlonCD!

 Same problems! Queue increases.

I looked to the code again, and changed (and recompiled) again with this little change in the code.
That little change <= instead of < makes things work!


![image](https://user-images.githubusercontent.com/24378221/104259744-bf6b3580-5460-11eb-954e-833229c28d47.png)

**Comment by VorlonCD** [comment]
@balqosz - what do you have your camera and AI Server min and max thresholds set at?

**Comment by VorlonCD** [comment]
The original code logic still seems ok to me but I'm willing to be wrong - It **only** uses the deepstack URL min confidence if the value in the URL edit box is **anything OTHER than 0-100**.   Otherwise, it uses the CAMERA min confidence.

I still cant make it crash after being SURE that min_confidence is actually being sent to deepstack server.   But the exact value you are setting it to could be important.  

Grab the latest github commit - I added some debug code for you to send me.

In the log, just before your next deepstack failure, look for the following lines.  Send me that and any any lines below it including the first error you get:

`DEBUG> (1/6) Uploading a 216753 byte image to 'DeepStack' (URL_LowerThresholdOverride=40,Upper=100)(0.4) AI Server at http://10.0.1.99:84/v1/vision/detection
DEBUG> (2/6) Posted in 2647ms, StatusCode='OK', Received a 120 byte JSON response: '{"success":true,"predictions":[{...'
`

**Comment by balqosz** [comment]
Hi VorlonCD:

 May be I have good news! May be I finally tracked it.

Inverting "," to "." in regional settings dialog box (in Windows control panel) makes all work fine.

Before making that change, I tried to follow the steps you detailed, but I couldn't find the line with "2/6" in the log

So it seems that the problem could be that we must take into account which is the decimal separator that is being used in the Windows regional settings.

**Comment by VorlonCD** [comment]
WOW good detective work!   I just fixed it in the latest commit by always trying to replace a comma with period before sending min_confidence setting to Deepstack.  (because 45% gets converted to "0.45" before sending, so it would have been 0,45 that deepstack did not know how to convert to a 'float' number.)

**Comment by Mrdindon** [comment]
Excellent !!!!! Thanks 👍

**Comment by Mrdindon** [comment]
So that might be the same sort of issue I' having here : 
![image](https://user-images.githubusercontent.com/5002201/104326761-151efc80-54b8-11eb-80d2-3b112e987912.png)

**Comment by VorlonCD** [comment]
@Mrdindon  - A comma is valid for a filename, so that shouldnt matter.   It might not be valid for the URL?    You could try @balqosz solution above as a test. 

But if you also had History tab > Restrict at source enabled, it could have crashed deepstack, causing the URL error.  Does re-starting it fix that URL error part of the error?

I see from the error "The path is not of a legal form." that you may not have the NETWORK FOLDER set correctly for the that camera action. 

Here is the latest version with the fix from above and a tweak to let you know you should have a valid network path set in camera settings.

[AITool-VorlonCD-v2.0.533.zip](https://github.com/VorlonCD/bi-aidetection/files/5802966/AITool-VorlonCD-v2.0.533.zip)

**Comment by balqosz** [comment]
Thank you VorlonCD! Version 2.0.533 is working as expected!!!

**Comment by Mrdindon** [comment]
sorry I had to delete my previous post there was a pwd exposed :P 
So maybe the file name issue I have now is not related to the coma but I don't understand why I have path issues... 
could that be related (see below). Also, just a quick question, do you think it would be better if instead of having the variables name and there value only when you click on it to have instead a button that when you press it, a window open whit the variable names and their value next to it ?

![image](https://user-images.githubusercontent.com/5002201/104356712-43153880-54da-11eb-9329-d4e68a43f09a.png)

**Comment by balqosz** [comment]
Mrdindon, change your password. That password is present in mails already sent by github.

> sorry I had to delete my previous post there was a pwd exposed :P

**Comment by Mrdindon** [comment]
Yup... thats ok thats just test Im doing here :)
