### ISSUE TITLE
Odd behaviour - resolution of BI cam changing randomly

### ISSUE THREAD

**Issue by Yonny24** [VorlonCD/bi-aidetection#149]
I have 3 Eziviz 3CWN exterior cams.

Been working great until the last few days. BI would randomly swap between 1920x1080 and 1280x720.
This screws up my masks for the AI tool and start getting loads of alerts outside my normal hi-def mask as it does not match the low-res.

Very odd indeed.
The BI would sometimes default to 1280x720 and if I open the Ezviz cam app it would revert to the high def without any changes from my part.

Not sure where the issue lies yet.

Anyone else seen this behaviour?

Thanks

**Comment by balucanb** [comment]
YES!! Been having that issue for 2 or 3 BI Updates now. You may be able to go back a release or two and fix it, or @VorlonCD has released a new version of AI-Tool that lets you scan your folder where your snapshots go: it will find all the different sizes and then you can draw the mask and it will save it to all sizes. I am using it and it has fixed the issue by 98%. I still have the issue randomly but it is very infrequently and may be due to issues with BI vs AI-Tool.

**Comment by Yonny24** [comment]
What version of AI tool are you on?
Mine says 2.0.570.7687 built on 17/01.

Is there a newer zip?

Thanks

**Comment by balucanb** [comment]
> I am using the one before this one, but here is one he just released about 8 hours ago. [#122 (comment)](https://github.com/VorlonCD/bi-aidetection/issues/122#issuecomment-763818039)

Here is the history on the change-  https://github.com/VorlonCD/bi-aidetection/issues/132

**Comment by Yonny24** [comment]
Thanks. Just updated the AI tool and blue iris. Lets see how it behaves now

**Comment by VorlonCD** [comment]
Note you have to re-create your mask for each resolution image your camera might spit out.  You will see a dropdown to select known resolutions in the custom mask tool.

**Comment by balucanb** [comment]
I went back and checked the version in the manifest file and I am running the one you have so you should have the options I am talking about if you DL'ed the newest one, I grabbed it earlier but got busy. I am going to load it up now. Good luck.

**Comment by Yonny24** [comment]
Yes I see the options in the drop down now and also in Settings the 2 masks created with the 2 resolution options.

Thanks very much!

**Comment by balucanb** [comment]
Also @Yonny24  go to issue 132 (from my post above) and start from the bottom of the thread and count 16 posts up there is one talking about a fix for the detection.py in Deepstack- I only mention it because I found my problem was a combination of BI/AI and DS issues. I went back to running the WIN version, if you are still doing the Docker thing it may not apply- Just read it and it will be clear.

**Comment by VorlonCD** [comment]
@balucanb - I finally noticed "Be all you can be" :)

**Comment by balucanb** [comment]
You win the prize!
