### ISSUE TITLE
Could not determine CPU/GPU type in C:\DeepStack\server\server.go?|26|1||5

### ISSUE THREAD

**Issue by fireport** [VorlonCD/bi-aidetection#157]
I just installed DeepStack-Installer-CPU.2021.01.beta on my pc and when I start aitool I see the error in the subject.
I tried test image and recognition it's ok.
Can this error harm the blueiris image recognition?
Thank you

**Comment by balucanb** [comment]
I can't help you with the error but there is a newer version of deepstack- 2020.12.beta

**Comment by TrunkMonk** [comment]
I had a different problem that was related to my cpu. 
Have you tried the noavx version of deepstack instead of the latest?

Instead of pulling "deepquestai/deepstack:latest", pull "deepquestai /deepstack:noavx"

**Comment by VorlonCD** [comment]
@fireport - the error only happens if you are using an older version of Deepstack (WINDOWS).  Has nothing to do with docker version.   However the version you posted seems to be the latest?     Its a harmless message anyway.

Maybe using an old build of AITOOL?   Latest:
[AITool-VorlonCD-v2.0.626.zip](https://github.com/VorlonCD/bi-aidetection/files/5900241/AITool-VorlonCD-v2.0.626.zip)

This is the latest CPU version - **2021.01**
https://github.com/johnolafenwa/DeepStack/releases/download/0.2-beta/DeepStack-Installer-CPU.2021.01.beta.exe

This is the latest GPU windows version - **2021.01.1**:
https://deepquest.sfo2.digitaloceanspaces.com/deepstack/DeepStack-Installer-GPU-Beta.2021.01.1.exe

**Comment by fireport** [comment]
Dear VorlonCD as I wrote in the first post I already had Deppstack 201.01.beta.
After installing the version that you suggested above the error related to finding which type of Deppstack I have disappeared but now in the log I have this message when I do the test
 `Positions (subitem4) ='1079,109,1438,1195;103,352,770,1188;670,319,1101,1091;687,305,907,713;158,665,600,1196;1389,820,1517,1001;5,5,1595,1160;135,662,599,1197;0,813,244,1200;738,734,1099,1162;65,845,1057,1198;0,855,48,1040;735,902,1084,1159;1,865,45,1039;203,953,598,1199;1,689,271,1200;390,623,513,735;0,855,48,1037;175,692,650,1192;432,640,506,712;99,645,342,1022;0,976,41,1042;4,686,449,1200;1,708,191,911;1398,652,1509,967;14,670,287,969;0,978,41,1037;1325,852,1399,1124;', Detections (subitem3) ='Person (90,44%); Person (83,06%); Person (78,93%); Person (41,55%); Person (2,42%); Potted plant (75,20%); Scene [Nursing_home] (51,72%); Handbag (35,27%); Dining table (25,79%); Chair (20,54%); Bench (14,44%); Vase (13,24%); Bench (12,45%); Cup (8,46%); Chair (7,90%); Handbag (7,45%); Tie (6,81%); Bottle (4,80%); Bench (2,94%); Tie (2,89%); Handbag (2,73%); Cup (2,29%); Dining table (2,12%); Dining table (1,97%); Potted plant (1,61%); Dining table (1,38%); Bowl (1,13%); Handbag (1,06%)': Riferimento a un oggetto non impostato su un'istanza di oggetto. [NullReferenceException] Mod: ToString() Line:1594 (pictureBox1_Paint)`
thank you

**Comment by VorlonCD** [comment]
Try making sure you have a camera called DEFAULT in the list.   Its "file starts with" setting should be empty.
That error could also happen when you have renamed a camera and scroll back through the history list created before you renamed it.

**Comment by fireport** [comment]
Thank you VorlonCD. Renaming a camera in default camera fixed the problem
