### ISSUE TITLE
Custom model log error

### ISSUE THREAD

**Issue by bmorgan99** [VorlonCD/bi-aidetection#159]
It seems to be working, but I keep getting this error in the log:

> ... AI URL failed with ' Got http status code 'NotFound' (404) in 2ms: Not Found' - for 'DeepStack_Custom' failed '96' times.
> Disabling: 'http://127.0.0.1:80/v1/vision/custom/YOUR_CUSTOM_MODEL_NAME_HERE'

At one time I had a custom model and also tried using AI Tool to start deepstack, but I've removed both.
Removed everything but the essentials in the Deepstack config area.  Manually removed what seemed related from the json settings file but it comes back.  Made sure AIT was down before editing.
 
DS  CPU.2021.01.beta
AIT v2.0.626

**Comment by VorlonCD** [comment]
Why does the url still have 'your custom model name here'??  Obviously that needs changing.   And there is some other back end config details you will have to find help on in deepstack docs or forums.

**Comment by bmorgan99** [comment]
Thats the funny part.  I deleted everything in the ait deepstack section.   Don't understand how it comes back.  I start deepstack with the minimal command line switches.  No mention of custom models.

**Comment by bmorgan99** [comment]
![image](https://user-images.githubusercontent.com/29981976/106633606-995b2180-6544-11eb-8ea9-5a28d7e21544.png)

**Comment by VorlonCD** [comment]
Hmmm.   What happens if you let AI tool start DeepStack for Windows (just as Jeebers intended)?

Remove any extra AI servers you did not specifically configure in Settings > EDIT button.

Disable the external deepstack startup script.

Enable Automatically start checkbox in DEEPSTACK tab.

Hit Deepstack tab > START.

If those mysterious YOUR CUSTOM MODEL HERE url's keep appearing, I think I'll need logs.

**Comment by bmorgan99** [comment]
Not sure what I had done, but we rollin' now.  It says emphatically that deepstack is NOT RUNNING, but it is and everything is functioning with no other errors.  What is your method for checking?
