### ISSUE TITLE
Crash when entering non-integer values as settings

### ISSUE THREAD

**Issue by MaleNurse** [VorlonCD/bi-aidetection#176]
When trying to figure out why people detected were being labeled as irrelevant, I tried setting the "Limit Size Percentage" minimum from 1 to 0.5 and a crash occurred due to a format exception. This is reproducible on other forms such as "Cooldown Secs" by adding non-integers.

Log:
[crash.txt](https://github.com/VorlonCD/bi-aidetection/files/5990174/crash.txt)

**Comment by VorlonCD** [comment]
Yup, I dont check for that case, needs to be whole number.     To troubleshoot, go to History tab > select item > click PREDICTION DETAILS.  You will see a lot of troubleshooting info for each prediction and the final result.

0 should disable the check I think.

There is some bug right now but only if you have duplicate objects (Two objects that are within 85% the same size get merged together and the newest prediction wins, but the bug is that the duplicate doesnt abide by any "Dynamic" masking you may have set up)

**Comment by MaleNurse** [comment]
@VorlonCD Cool, yeah, 0% is the way I went with it and that caused an alert when restesting the image. I'm not sure if you're even sending this to the log, but I didn't see a specific result in terms of what that calculated percentage was. Maybe it's only in trace mode (I'm in debug)? Feel free to close this issue if you want, though.

**Comment by VorlonCD** [comment]
History tab > Prediction details, see these columns:

![image](https://user-images.githubusercontent.com/7512113/108106861-81af8d00-705c-11eb-9255-0bd46558380e.png)

**Comment by MaleNurse** [comment]
Scroll to the right?! My mouse doesn't do that! Oh, wait, it does. Still! How dare you ask me to break from my inattentive laziness when searching for information! 

*sigh.* Sorry for another bone-headed oversight...

**Comment by VorlonCD** [comment]
Fixed crash, force integer for all the values.   If you enter .5 it will convert to 1.
[AITool-VorlonCD-v2.0.716.zip](https://github.com/VorlonCD/bi-aidetection/files/5992844/AITool-VorlonCD-v2.0.716.zip)

**Comment by MaleNurse** [comment]
Looking great so far!
