### ISSUE TITLE
Can't add a 7th server

### ISSUE THREAD

**Issue by clarkhaskins** [VorlonCD/bi-aidetection#181]
I am trying to add multiple copies of my main Deepstack object server to allow for a connection pool if you will, however, I can't seem to be able to add a 7th server. I can add it, it shows up in the list, when I then attempt to set the URL correctly and hit save, it disappears.

![image](https://user-images.githubusercontent.com/12701800/108262852-b8e87180-7122-11eb-8cc3-d678859397b2.png)

**Comment by VorlonCD** [comment]
When you first download the ZIP file you must right-click > Properties > **UNBLOCK** checkbox.

That has to be done BEFORE extracting all the files.  (otherwise you have to unblock all individual exe/dll files).

Also, if you have a weird permissions thing going on in the folder (which is sometimes the reason for a read-only issue like that), you should be able to fix simply by making a copy of the whole folder:

1) Make copy of AITOOLS folder
2) Rename original to BAK
3) Rename COPY back to AITOOLS.

**Comment by VorlonCD** [comment]
@clarkhaskins  - let me know if making a copy of the folder fixed it.
