### ISSUE TITLE
Multiple deepstack instance

### ISSUE THREAD

**Issue by JayL-F1** [VorlonCD/bi-aidetection#189]
I'm having trouble running two instances of deep stack in ai-tool

deep stack gpu 2021.01

ai tool 2.0.627.7696

when I go in the deepstack tab and add another port: 82,83

click 'start'
it seem to be fine, it shows two command line and URL and 'running'

but then after the first event is analyzed I get an error

stderr.txt:

Process Process-1:
Traceback (most recent call last):
File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\process.py", line 297, in _bootstrap
File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\process.py", line 99, in run
File "C:\DeepStack\intelligencelayer\shared\detection.py", line 138, in objectdetection
os.remove(img_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\DeepStack\\83e674a1-5439-4a0c-814c-3449f9b86bae'

**Comment by VorlonCD** [comment]
Same thing I get when I run more than one copy.   Although I think it takes a while to happen for me.  Even with the latest build.  Log a bug with Deepstack:
https://github.com/johnolafenwa/DeepStack/issues

Note that I posted a fix for that error a while back, but I have no idea if it is still fully compatible with the _latest_ release since I haven't compared the code yet.  Test **detection.py** at your own risk.
https://github.com/johnolafenwa/DeepStack/issues/51#issuecomment-756788251

**Comment by Tinbum1** [comment]
see also https://github.com/johnolafenwa/DeepStack/issues/63
