### ISSUE TITLE
Notification Issue

### ISSUE THREAD

**Issue by radiocooke** [VorlonCD/bi-aidetection#190]
Let me start by saying I am very new to this so it could totally be user error. I have BI, DeepStack and AITool setup. The version of AITool is 7.0.701.7715. If a trigger is fired in BI, almost everything works as it should. I see the external alert in BI, however, I get no alert email or push on my mobile device (yes I have both alert types setup in BI). 

Here is where is gets interesting. If I go back into AITool and open the same camera I just got the trigger for, go to Actions and click Test, it runs a test against the same image of me that created the original trigger. That goes right to BI and I get all the alerts including the email and push I have setup. 

Is it possible that the test button is doing something slightly different and as a result BI does not initiate the email and push alerts except when I click Test?

**Comment by VorlonCD** [comment]
The test button just uses the last detection if there is one.   

Its probably a config issue in BI so you would want to ask their support or forums. 

From AITOOL I can take a quick look - send screenshot of your actions screen, and see if you can isolate part of the log where the BI URL was triggered but you didnt get notifications.  Maybe the cool-down is affecting things?

Also you could use pushover or telegram for notifications rather than BI

**Comment by radiocooke** [comment]
I think it was user error, its odd that it worked on the test but not with real activity, but I was able to get it working consistently by changing the Trigger Sources and Zones setting in BI. Thank you for your help
