### ISSUE TITLE
mqtt error :     Unable to connect to the remote server [WebSocketException] Mod: <Connect>d__14 Line:306

### ISSUE THREAD

**Issue by bbrendon** [VorlonCD/bi-aidetection#198]
Version 2.0.627.7696

When I click "Test" in the dialogue box below i get : Failed see log for detials.

Log error :     Unable to connect to the remote server [WebSocketException] Mod: <Connect>d__14 Line:306

I made sure the computer can access the port 1883 and that the windows firewall is off.

![image](https://user-images.githubusercontent.com/6364477/110715978-2126f200-81bb-11eb-8d1a-59464328f58c.png)

**Comment by bbrendon** [comment]
I found v846. Same issue but different error:
    Unable to connect to the remote server [WebSocketException] (In MQTTClient.Connect:306 >  > ClientConnectAsync >  > ClientConnectAsync >  > AdapterConnectAsync > Adapter.MqttChannelAdapter.WrapAndThrowException(Exception exception))

**Comment by VorlonCD** [comment]
Does it work if you enable TLS checkbox?

Double check firewall is off ?

Also Reboot both machines

**Comment by bbrendon** [comment]
Rebooted. Same error.

tcpdump shows packets being received on the mosquitto box. But ` mosquitto_sub -t '#'` shows no output.

**Comment by Boh1** [comment]
I appear to have the same error. Also rebooted both my boxes. This was an install over a preexisting AI Tools but everything else works fine. 

`10-Mar-21 11:11:07 AM PublishAsync MQTT: Unexpected Topic 'ai/Deck/motion' Payload 'No Detections Found': Unable to connect to the remote server [WebSocketException] Mod: <<PublishAsync>b__0>d Line:230:41 Error AITOOLS.EXE 5 2 12 False AITool.[2021-03-10].log`

BI is on the same box as AI Tools and has no issues reaching the same MQTT server. Port 1883 and mo creds or TLS required by my Mosquitto container.

**Comment by VorlonCD** [comment]
Antivirus disabled for testing?

Lets do a start fresh:
1) Download the last zip again from one of the recent threads.
2) right-click > properties > UNBLOCK the zip file (important to do before unzipping!)
3) Overwrite all the files in AITOOL folder

If still not working, hit RESET button on settings tab, reconfigure a new camera + mqtt settings, and test.   Note that a reset does not delete the settings, just renames the _SETTINGS folder and re-creates.  You can still revert back by renaming the _SETTINGS+DATE folder you will see in the AITOOL folder after resetting.

Otherwise, can someone post instructions how to setup and test MQTT on a windows box?  If I could avoid docker, etc that would be good.  I dont have a server set up unless you count whatever BI has built in.

**Comment by Boh1** [comment]
I tried all of the above and still get the same error. 

If you need a quick setup of an MQTT server on Windows, this is not a bad resource: [How to Install The Mosquitto MQTT Broker on Windows](http://www.steves-internet-guide.com/install-mosquitto-broker/)

**Comment by bbrendon** [comment]
Using https://github.com/VorlonCD/bi-aidetection/files/6071586/AITool-VorlonCD-v2.0.845.zip

I installed it on another computer with AV disabled. Same results.

I'm running mosquitto on a linux host. If you want, I can open my mqtt to you with IP ACL if we can somehow PM eachother.

**Comment by Boh1** [comment]
Okay, someone found a workaround that would seem to narrow down the bug. All you need to do is enter anything for the creds. Then it appears to work.0

I guess the current code doesn't handle nulls for these fields (which are perfectly valid in MQTT-land).

**Comment by VorlonCD** [comment]
@Boh1 - Good find!!   Not sure if the issue is on my end or the MQTT.NET GitHub library I use.   But my next version will always try to connect with username / password, **even** if they are just empty strings.  (before it would have been null as you mentioned)

In the code, if there was not a username specified, I didnt call ".WithCredentials()" because I didnt think it was needed.  Now it will always be called.

**Comment by bbrendon** [comment]
Thanks guy!

This is awesome!

```

Mar 11 12:00:53 bruh/sensornode2 {"state":"OFF","humidity":"1.00","ldr":"16","temp_b":"54.21"}
Mar 11 12:00:56 ai/front-left-hd/motion Person (76%),Person (76%),Car (62%)
Mar 11 12:01:00 ai/front-left-hd/motion Person (69%),Person (41%),Car (67%),Car (17%),Car (16%),Car (16%)

```

**Comment by VorlonCD** [comment]
This one shouldnt have the same issue.  (you shouldn't have to enter a username to get it to work)
[AITool-VorlonCD-v2.0.930.zip](https://github.com/VorlonCD/bi-aidetection/files/6135867/AITool-VorlonCD-v2.0.930.zip)

**Comment by Boh1** [comment]
Thanks for this!

**Comment by VorlonCD** [comment]
This one fixes mqtt cancel issue:
[AITool-VorlonCD-v2.0.988.zip](https://github.com/VorlonCD/bi-aidetection/files/6176514/AITool-VorlonCD-v2.0.988.zip)
