### ISSUE TITLE
Anyone know of other APIs out there good for identifying wildlife?

### ISSUE THREAD

**Issue by 162884** [VorlonCD/bi-aidetection#211]
I'd like to use a AI Tool to identify various wildlife. I live in a rural area and I would like to keep up with coyotes, deer, possums, raccoons, skunks, rabbits etc. Currently using Deepstack, AWS Rekognition and Sighthound. I don't believe any of those have the relevant objects I'm looking for. In fact, I've been unable to find a list of objects that each of those are capable of identifying.

This tool is just fantastic, it is changed everything about how I use Blue Iris. I appreciate it so much and would love to donate to @VorlonCD to show my appreciation!

**Comment by VorlonCD** [comment]
I could never find a full list for AWS Rekognition.  For deepstack, see CLASSES here:
https://docs.deepstack.cc/object-detection/

And of course if you wanted to put in the work you could train your own Deepstack models.
https://docs.deepstack.cc/custom-models/

I havent looked into this, but since AITOOL supports DOODS, and DOODS lets you change the detection model, there may be another custom model available you can switch to that better detects animals?
https://github.com/snowzach/doods

**Comment by 162884** [comment]
Thanks for the reply and the additional information. I've tried getting DOODS up and running on my QNAP NAS in Docker, but so far I've been unsuccessful. I'll keep trying though!

**Comment by VorlonCD** [comment]
I had it going on Windows docker when I was testing.  The only thing I remember is that I HAD to use the default port it expected rather than changing to a custom one.   This was a while ago so this bug may no longer exist.
