### ISSUE TITLE
Refinement server Time out error

### ISSUE THREAD

**Issue by 162884** [VorlonCD/bi-aidetection#214]
I just recently started using refinement servers. I have noticed some time out issues and have manually updated the settings file to try and allow more time. I'm still getting these errors occasionally, I'm wondering if there is something more I should do. The refinement server in this case is Sighthound_Vehicle.

2021-03-25 12:53:36.187555|Error|AITOOLS.EXE|WaitForNextURL|Deepstack_Objects:192.168.1.18:32785|Garage_AI|None|    ---- URL request for REFINEMENT AI Server timed out, but only '0' of '1' available. (8056ms - Setting in AITOOL.SETTINGS.JSON 'MaxWaitForAIServerMS' and is set to 8000)|87279|3||50

**Comment by VorlonCD** [comment]
Well, if you want it to wait longer than 8000 ms for the refinement server to become available you can increase that value - I think you can change it in the sighthound URL edit screen rather than the JSON file like the message says.    I think it just means that the server was busy handling other requests.   If you dont want that to be an "error", uncheck ERROR in the URL edit screen.

I have mine set to 10000 and never see the error with Sighthound person and vehicle.   Be aware a high setting might cause your image queue to build up while waiting for the refinement server to be available - thats why I put in the limit in the first place.
