### ISSUE TITLE
Possible Bug: Prediction Tolerances have no effect.

### ISSUE THREAD

**Issue by balucanb** [VorlonCD/bi-aidetection#219]
Version: v2.0,1015

Set up: Running all items on a Windows machine.

Item: Prediction Tolerances settings

Problem: 
Changing the min. tolerance appears to have no effect. i.e., If you change the min from 30 to 20, save it. The number will change in that setting box however, it does not change the min. anywhere else on any other setting.

My assumption is this is the universal start point for the camera and if you change it there it would change your setting everywhere. even if I am not understanding the setting, I see no other place that changes except in that setting window which would indicate to me that there may be a bug someplace.

**Comment by Tinbum1** [comment]
It's like a master check or gatekeeper. I would be somewhat upset, that all the time I had spent setting up each camera individually changed.

**Comment by balucanb** [comment]
> It's like a master check or gatekeeper. I would be somewhat upset, that all the time I had spent setting up each camera individually changed.

Tinbum1 I probably  don't understand your reply. I understand it is a master, using that thought if you change something there shouldn't it then make that change everywhere? If not then I don't understand it's purpose.

**Comment by Tinbum1** [comment]
I wouldn't want it to change any of my camera settings- if it did that I would have to go back and readjust every camera individually. I'm not quite sure on the purpose but I'm sure their will be a reason.

**Comment by VorlonCD** [comment]
They shouldn't be changing for any of the "CAM\DEFAULT" relevant objects for each camera, right?

Everything has to pass through that first (like a gatekeeper), so if for example you have the min threshold for PERSON in CAM\DEFAULT set to 40%, it makes no sense to change CAM\MQTT to 30% because it would never have had a chance to be tested against.   So in MQTT, TELEGRAM, etc lists you can only further refine **within** the CAM\DEFAULT tolerance range.   It will force it to be whatever set in \DEFAULT if you set it outside the tolerances for that.

**Comment by balucanb** [comment]
I know I am making this harder than it is fellas so sorry for that. Let me do a check on learning.. If I have PERSON set to 30% in the default setting that is the base so to speak, nothing would happen unless it is at least 30%, If I then set PERSON to 50% for Telegram I would only get alerts sent there that hit the 50% min limit however, I assume that any PERSON that was at least 30% would still show a alert image inside AI-Tool in the History.

**Comment by VorlonCD** [comment]
You got it!
