### ISSUE TITLE
Relevant Objects automatically updating for all cameras

### ISSUE THREAD

**Issue by travmo** [VorlonCD/bi-aidetection#226]
Hey there,

The issue I've come across recently is that when I add or remove an object from Relevant Objects in the Camera settings, it also adds/removes it from the other cameras settings as well. So if I add "Dog" to Backyard, it also adds "Dog" to Frontyard, Garage, and Driveway.

Initially I thought maybe my Settings folder items were corrupt somehow, so I just recreated it all as a fresh setup, however today it started doing it again. I'm speculating, but I think it started after I used the "Apply to" option and selected my other cameras. I did that to avoid setting up Actions and Prediction Tolerances on every camera to save time. If I get a chance, i'll do another fresh setup and not use that feature to see if I can narrow it down, but wanted to bring it up in case i'm not the only one running into this.

Thanks again for your work in this project, I really appreciate it!

**Comment by VorlonCD** [comment]
You might have an old build, sounds like something that was fixed.   Try this:
[AITool-VorlonCD-v2.0.1036.zip](https://github.com/VorlonCD/bi-aidetection/files/6254963/AITool-VorlonCD-v2.0.1036.zip)

When a relevant object list sees an object detected not already in the list, it WILL add it, but it should be "disabled" so you can enable it if you like later.

**Comment by sea3pea0** [comment]
I am having the same issue. If I make any changes to relevant objects for any camera it applies to all cameras. @VorlonCD I tried with the version you posted and I'm still getting the same results. On a side note and not sure if it hasn't already been requested, it would be helpful to be able to specify maximum and minimum percentage of image for each object in the relevant objects section. That way I could prevent that bug that walks across my camera from being detected as a cat that takes up 50% of the image. Thank you kindly

**Comment by VorlonCD** [comment]
I'm not seeing the relevant object issue.   But if you used one of the first builds with the new relevant object dialog, that WAS a problem.   Objects would be linked together from list to list.   RESET button should fix.   Note that it gets the defaults from the DEFAULT camera.

**Comment by sea3pea0** [comment]
I'll try playing with the configuration a little more when I get the chance. In Blue Iris, I'm using the cloned camera method for dealing with triggers to keep the alerts list free of duplicates. My clone cameras have the same name as the masters except I add a "_c" as a suffix to the clone/trigger cameras. In AI Tool the cameras I have added are the camera names without the "_c". I see in AI Tools Logs complaints about not finding matching cameras that match the trigger images that have a "_c" in the filenames, but also in the logs it says that the images are matched to the closest name which are the cameras that I have added without the "_c". So everything works for the most part because the camera names begin with the same string. I am wondering what naming convention I should use in AI Tool for a cleaner setup and also to see if perhaps properly named cameras may magically fix this problem for me.  So let's say I have camera_1 as the master and camera_1_c as the trigger. Should I put camera_1_c as the name of the camera in AI Tool and then camera_1 as the BICamName? I'd figure that I'd put camera_1_c as the prefix as well, but I guess that shouldn't matter as long as no other camera's names start with camera_1. I tried all this a handful of versions back when I started using the clone camera method but ended up with some weird problems in AI tool where alerts were getting mixed up between cameras so I went back to leaving the "_c" out of the names of the cameras in AI Tool since it worked that way

**Comment by VorlonCD** [comment]
Camera name and BI Camera names in AITOOL shouldnt matter.   But the "Input file begins with" might matter.   Try adding a period . after the camera name to force it to pick it up.   Like `CAMNAME_1_C.`     And if each camera in BI is configured to a different INPUT PATH, then you can set those input paths in AITOOL for it to find the camera if it doesnt any other way (It will match based on the path the JPG file is in rather than the name)

If still not working as you need, I would need to see the "GetCamera" log entries and exact names of your BI cameras and AITOOL settings.

Bonus:  I added the ability to limit the size of each object type in relevant objects - Does this work for you?
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

**Comment by sea3pea0** [comment]
I'm not completely sure what fixed it, but I deleted my settings again and set things up with the naming convention you recommended and it's working. I'm able to adjust relevant objects independently for each camera. Thanks! Nice work on the installer too!

**Comment by VorlonCD** [comment]
flying away on a wing and a.....
https://www.youtube.com/watch?v=B4JCehDOy54

**Comment by sea3pea0** [comment]
Not sure at what point but the problem reappeared for me. Somewhere between adjusting confidence thresholds and using the "apply to" feature, now once again when I change relevant objects and confidence thresholds, immediately after making the change I can see that the change is applied to all cameras. 
Here's an image of my camera settings and some logs:
![Settings](https://i.imgur.com/aMGF5rc.png)
[GetCamera Logs](https://gist.github.com/sea3pea0/d8520a78bab398f20470a35c60ab2aa6)

**Comment by VorlonCD** [comment]
HA!  "Apply to" was the key.   I needed to clone the objects rather than referencing them:

https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

**Comment by travmo** [comment]
Hey there! Sorry for going MIA after submitting this issue, life got the best of me. I got a chance to test this latest build and while I did need to create a fresh configuration, it appears to be working flawlessly! I appreciate you sea3pea0 for helping isolate this behavior, and VorlonCD for putting in the work to get it fixed so quickly. Love this tool, idk what i'd do without it!
