### ISSUE TITLE
Error when deleting history item

### ISSUE THREAD

**Issue by jscoulter** [VorlonCD/bi-aidetection#240]
Hi.
I have been getting the following error and its preventing alerts being triggered in Blue Iris as well as not sending to Telegram.

DeleteHistoryItem>> Error: StackDepth=22, TID=1, TCNT=18: 'c:\blueiris\ainput\cam1.20210502_081234278.jpg' - attempt to write a readonly database [SQLiteException] Mod: <DeleteHistoryItem>d__51 Line:245:17

I COULD prob. download the source and fix it, but thought I would log it in case its a know issue and also to let you know.
Is there a work around?,

Thanks Jeremy

**Comment by VorlonCD** [comment]
Task Manger > Details tab:   Is there more than one copy of AITOOL.EXE running?   As a service for example?    The second copy would have "read only" access to the database as the error states.   But I didnt think you would get that error if a second copy starts because the second should know about the first anyway.

Do you have the latest version?
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

Database corrupt?   Delete or rename \_SETTINGS\AITool.Database.SQLITE3

**Comment by VorlonCD** [comment]
Hey, if you downloaded the source and fixed it, let me know!   You are part of the solution.
