### ISSUE TITLE
Error Status Anomaly

### ISSUE THREAD

**Issue by Village-Guy** [VorlonCD/bi-aidetection#262]
DeepStack page is showing an error but everything seems to be working fine

![image](https://user-images.githubusercontent.com/70348613/125169925-56147700-e1a4-11eb-86e9-659af76a3e57.png)

**Comment by Tinbum1** [comment]
I have the same. Deepstack opens with 2 python instances per port but it then closes down all but 2. I logged this with Deeptsack months ago but they haven't come up with a solution. It can be very temperamental using multiple ports with the GPU version but then often it runs great. I found increasing the paging file size helped but that could have been coincidence.

**Comment by VorlonCD** [comment]
Hi Stop, then Start and wait a minute.   Send me any recent errors from the log window, and also hit STDERR.TXT button and send me that file if it exists.

For every copy of DeepStack, there should be 2 copies of `Python.exe` running.  There would be an error if less than 4 copies of python.exe were running in your case since you are using 2 ports.   This is what one copy looks like when you use Process Explorer or Process Hacker to see the process tree:

![image](https://user-images.githubusercontent.com/7512113/125176089-c1f3e100-e19e-11eb-8d57-b7027a0c8551.png)

Try cutting it down to 1 port to see if the same thing happens.   More than one copy running never seems to be terribly stable for some reason.  I recommend trying to find a second device to run the second copy of deepstack on.  I run a second copy on my synology NAS and raspberry pi, and am trying to get an nVidia NANO set up for a 3rd.

**Comment by Village-Guy** [comment]
I have resolved this issue by regressing my system back to running DeepStack inside a Docker environment.  It appears more efficient and reliable than running in a Win 10 environment when more than one copy of DeepStack is running on the same processor.
