### ISSUE TITLE
AITool.2.0.1205 Memory Leak, Pushover triggering objects not working

### ISSUE THREAD

**Issue by cmdwhoami** [VorlonCD/bi-aidetection#264]
I had some issues with 2.0.1205

I'm using DeepStack GPU running 3 instances from AITool 

- memory would reach 90%+ after 12hrs (12gb installed) 50% usage is normal

- pushover triggering objects and setting times did not seem to work. I set it to only trigger pushover alert for [person] between 23:59:59-04:59:59 but was getting notifications at all times for all relevant objects. setting time in the Send Alert Images To PushOver section worked though.

- AITool would not auto start at boot. I think this may have been because I set DeepStack to "run this program as an administrator" in properties. (had the same issue with 2.0.942 until I figured out running DS as admin with the issue)

![aitool_memory_leak](https://user-images.githubusercontent.com/30704361/125709408-2f489bf7-02ff-4031-962b-cfbf57e1435f.PNG)

**Comment by VorlonCD** [comment]
Go to the Task Manager > Details tab.    I bet `AITOOL.EXE` is only consuming a fraction of that 5 GB.      The value on the Processes tab is usually combined memory usage from all Deepstack processes that AITOOL actually starts.  (If you have that enabled on the Deepstack tab)

I watched my memory usage for 2 days (I have 5 cameras) and I was only seeing a peak of 1 GB that eventually went back down to 600 MB.

BlueIris on the other hand was up closer to 10 GB.

Note that if you have a large queue of images waiting to be processed it will increase memory usage for a while, then release it when everything has been processed in the queue - It loads each image into memory and stores it for a little while to guarantee access to the file in the queue.  I guess there could be a memory leak.  (On the AITOOL status bar, watch "**ImgQueued**" max)

Its likely that `DEEPSTACK.EXE, PYTHON.EXE and REDIS-SERVER.EXE` are the ones consuming that much ram (All combined).

I've found that deepstack isn't all that stable when you run more than one instances on the same machine (and doesn't help overall performance all that much).    

**Run ONE instances of deepstack for a while for testing**.

Double check that AITOOL and Deepstack are not running "As administrator".   It should not be required, and might be a factor.

For the time issues, try resetting objects for each camera you are having trouble with:
* Click DEFAULT camera > Relevant Objects > RESET button  (This is the default for all other cameras when you hit RESET)
* Configure any object changes you would like for ALL cameras as the default
* Select each camera > Relevant Objects > RESET button
* Camera > Actions > Telegram > Triggering objects > RESET.   Now tweak any changes you need here.

@cmdwhoami  - Just a wild guess based on nothing but your avatar...  I watched the entire Mr Robot series twice.  But so far I've so far failed to get Kali Linux running on my nVidia Jetson.  Sadness.    :(

**Comment by cmdwhoami** [comment]
If I was confused before, now I'm super confused. 

1. Click DEFAULT camera > Relevant Objects > RESET button
I don't have a RESET button. The only RESET button I have is in the Settings tab left of UPDATE and it wipes literally everything and creates a back up file. I'm using latest version [2.0.1206]

2. I checked Task Manager > Details tab and AITOOL.EXE was using 5 GB
I added another 12gb of RAM to my system last night  just to see how high it would go to truly see if it was a memory leak and after running for about 12hrs the highest I saw it get was 12GB for total system. 5 of those GB's were from AITool but it would fluctuate between 4-5. But then I clicked the RESET button in settings tab wiping all settings so that was the end of that experiment.

3. So far I believe I've tried every possible combination of settings but still get pushover alerts for every detected object at all times of day.

What is the purpose of Camera>Relevant Objects>Dynamic Mask? I can't figure that one out.

I was wondering why every time I tried to delete DEFAULT camera it would pop back up. Now it makes a little more sense although I still don't fully understand how I should be setting Relevant Objects for DEFAULT cam. (Default/Telegram/Pushover/MQTT/Dynamic Mask). I understand how they work for SecCam_1 ect. with the exclusion of SecCam_1/Dynamic Mask, unless what Im thinking the settings for SecCam_1/Default should be, should actually be placed in SecCam/Dynamic Mask instead. Maybe that's my issue. But then that leaves me confused at to what SecCam_1/Default would be for. 

I read somewhere in here before that you wrote you weren't too knowledgeable regarding Linux. I find that hard to believe... since you wrote all this (AITool) for Windows which is pretty fkn impressive. In my limited experience creating things for Windows I've come to the conclusion Windows is complicated AF. I'm guessing you have no issue getting Kali going, its just Kali on a Jetson that's giving you problems.

I almost get the feeling you're slightly trolling me mentioning my avatar and Mr. Robot in the same sentence...  If not... it's a strange coincidence. My avatar is from a movie called whoami... It's a German film with an option for English subtitles. The Mr. Robot series was created based off that movie (whoami). I'm kind of get the impression you knew this though. 
I selected the username whoami because at that point in time my side hustle was selling questionable Chinese goods on online market places using multiples of accounts. Turns out PayPal doesn't appreciate that kind of behavior so to run multiple accounts you need multiple VPNs, user accounts and spreadsheets to keep track of everything to not create a link between accounts. I found that using a Chromebook running Crouton to run a CLI only version of Ubuntu in the background to run a fully functional VPN client to be a better option then VM's to keep cookies separated since I basically needed a google identity for every account already anyway.  Although I didn't use cmd whoami much, I found it fitting. ¯\_(ツ)_/¯

**Comment by cmdwhoami** [comment]
I got pushover working. not exactly sure what I did though.

**Comment by cmdwhoami** [comment]
Changes I made that could have made Pushover notifications work as intended for SecCam_3:
enabling Person in Default\Default
![1](https://user-images.githubusercontent.com/30704361/126039416-b56879ab-7271-4253-8110-0dce9dcfdc62.PNG)

Added these objects to Default\Dynamic Mask
![2](https://user-images.githubusercontent.com/30704361/126039559-530ca1d3-06c3-49c8-b03c-6600f5b626b3.PNG)

Adding [person] with threshold and time range I wanted to use for Pushover notification on SecCam_3 to Default\Pushover
![3](https://user-images.githubusercontent.com/30704361/126039599-bd191a9b-6b68-47b2-8496-78f336b67160.PNG)

Or adding these objects and enabling them in SecCam_3\Dynamic Mask
![4](https://user-images.githubusercontent.com/30704361/126039706-a18b26cf-eff1-47fe-a5f9-4ea86ac57866.PNG)


I'm thinking I must be misinterpreting the function of either Default\* or SecCam_3\Dynamic Mask

I was getting something in debug log that could have been a clue but I deleted those files. Its said something about something was missing. RelevantObjectManager:  pulling something from MQTT RelevantObjects or it would say pulling from Telegram RelevantObjects

**Comment by VorlonCD** [comment]
Ok, let me keep digging for a memory leak.    

You dont have some crazy number of cameras or a very high rate of images being processed do you?   (Status bar > History items XXX / MIN).   Screenshot your status bar.   And you haven't manually changed default MAX values for history or log directly in the AITOOL.SETTINGS.JSON file?  (MaxHistoryAgeDays (14) and MaxGUILogItems (5000))

Do you have BI set to keep images for a very long time without archiving them?   I think I have it set to never have more than 7 days worth of images before archiving to another un-monitored folder.   This can certainly affect how much ram AITOOL uses because by default the history database will store 14 days worth of detection's.

The default camera settings are used for any NEW cameras you create or when you hit RESET for Relevant objects.

This is the RESET button - you dont see it?   I would reset everything and reconfigure each just to make sure its not a factor for your pushover issue.

![image](https://user-images.githubusercontent.com/7512113/126049258-78664cd3-bbb6-43bd-8e9a-cd75a2db0a34.png)

In your screenshot, Person isnt checked??
![image](https://user-images.githubusercontent.com/7512113/126049918-a709891e-247b-44b2-8ff5-a761a88ba5e4.png)

The main CAMERA RELEVANT OBJECTS is sort of like the gatekeeper.   But if it gets past that, then you can further refine which objects trigger Pushover, Telegram, etc.

Dynamic masking feature - Imagine a car parks in your driveway that isnt normally there.   When dynamic masking is enabled, if an object is detected in the same area a configurable number of times, dynamic masking kicks in and prevents new alerts for a while.   Then when the object leaves the dynamic mask will be removed so that other things in that area are not masked by mistake.  (Thanks again @classObject ! )

I'll need relevant LOG entries if you think something is still misbehaving.

Nope, my Linux skills are seriously lacking.  I've just had basic experience getting PiHole and nVidia jetson working.  And getting LS to show hidden folders waay back in the good ol FTP warez days.    

Kali Linux on Nvidia Jetson isn't supported and I haven't figured out how to get the nVidia Cuda/SDK fully installed.  Will get back to it some day.  The  default OOTB image they provide seems to be crap.  Its Ubuntu 18.04 which is fine but  `apt get` seems to be crippled.  I cannot install any 3rd party tools like Docker or VNC/xfce4.   Apt update gives '**Unknown error executing apt-key**' for a number of the items.   I think basic OS updates get applied but anything else I try to install fails.   My google-fu is strong but has not helped so far.

I'd totally forgotten Mr Robot was based off a German show.   It was just a guess you liked it based on the avatar picture and name.   WhoAmI was an actual episode name.    No trolling.  Probably.   :) I got such a fucking kick out of MrRobot!

**Comment by cmdwhoami** [comment]
After testing for a week or so it appears the memory issue only has to do with running multiple instances to DS for parallel GPU processing.  Which leads me to the question, it running multiple instances the only way for parallel processing with DS?

The pushover issue I was having had to do with my misunderstanding of the purpose of the Default camera profile.
