### ISSUE TITLE
TelegramUpload>> ERROR: Could not upload image 

### ISSUE THREAD

**Issue by Jooced** [VorlonCD/bi-aidetection#28]
In 1.7.6 I'm getting an error every time a Telegram alert tried to send

```
TelegramUpload>> ERROR: Could not upload image T:\aiinput\Front.20200917_142715739.jpg to Telegram: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) [FileLoadException] Mod: <TelegramUpload>d__30 Line:1342:33
[1714:33:05]: Trigger>> Error: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) [FileLoadException] Mod: <Trigger>d__32 Line:1570:29
```

I've attempted to remove and re-extract the files again but it's still not working.

**Comment by petermai6655** [comment]
I'm experiencing the same problem.

**Comment by VorlonCD** [comment]
I assume you tried right-click ZIP > Properties > Unblock **before** unzipping?   Otherwise each file in the folder would need to be unblocked separately.  

Do both of you happen to have visual studio installed?   I wonder if it is a factor since one other person on ipcamtalk reported the same issue.    He could compile his own version of the fork and it worked.   He also had docker for windows installed that has its own copy of that Newtonsoft.json.dll file which may or may not be related.  If you DO have visual studio installed, try Help > Check for updates, install any updates and reboot to see if my version of the tool now works.    Otherwise, if you want to compile your own, make sure and go to Projects > NuGet > Update tab and install all the updates before compiling.

**Comment by Jooced** [comment]
I don't have VS installed and I used to have Docker for Windows but no longer. The Newtonsoft.json.dll file shows up all over the place on my system though from Duplicati, Handbrake and many versions in C:\Program Files\dotnet\sdk\NuGetFallbackFolder\

**Comment by petermai6655** [comment]
I didn't have VS installed either, but I went ahead and installed it and complied, and it works as expected now.

**Comment by youzer-name** [comment]
I was having the same issue and tried a bunch of things that VorlonCD suggested with no success. I also only was able to get it to work by compiling it myself in Visual Studio.

**Comment by VorlonCD** [comment]
I cant believe I didnt think of this.   The **AITOOL.EXE.CONFIG** file has DLL dependency versioning in it.   I have **not** been including that file because it also used to contain custom user settings.   But I'm now almost sure it is causing this issue.

@petermai6655 or @youzer-name, can you attach that file here for @Jooced to try?   Obviously make sure it doesnt contain any personal info, but I dont think it does since I havent been using that for a settings file for quite some time.  (The settings you see in it like blue iris server info are NOT used, they are legacy settings).

**Comment by petermai6655** [comment]
Here, try this.

[AITool_Config.zip](https://github.com/VorlonCD/bi-aidetection/files/5242771/AITool_Config.zip)

**Comment by Jooced** [comment]
Works great, thank you @petermai6655 

And @VorlonCD keep up the great work!

**Comment by Kryptonit3** [comment]
So Visual Studio is required to be installed in order to use your fork? Why is that?

**Comment by VorlonCD** [comment]
@Kryptonit3, oh you figured it out.  I was going to randomly say, Supes, watch "The Boys".  Good stuff.

**Comment by jdom** [comment]
I was going to comment the same thing, indeed you need to ship the config file as it includes the binding redirects

**Comment by VorlonCD** [comment]
Fixed in latest release:
https://github.com/VorlonCD/bi-aidetection/releases
