### ISSUE TITLE
High CPU usage while idle

### ISSUE THREAD

**Issue by apedance** [VorlonCD/bi-aidetection#316]
Hello,

I recently noticed high cpu usage while being idle.

No big changes have been made to the config.

![image](https://user-images.githubusercontent.com/4264240/158701166-5b1f8a1a-e9ba-4063-948f-24c10e4b53ea.png)

**Comment by VorlonCD** [comment]
Unlikely to be AITOOL itself, rather the Deepstack process that AITOOL starts.   If you fully expand like this is it ALL coming AITOOL or one of the sub processes?

![image](https://user-images.githubusercontent.com/7512113/158701875-50a32bb3-34e7-4377-b56f-3626ec27cf34.png)

Otherwise:

- Are any of your cameras looking in folders that have 1000's of files?   You would really need to limit how many files stay in those folders by telling blueiris to archive them somewhere else after xx days or size.
- Latest version of AITOOL is 2.1.6.0.:
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

**Comment by apedance** [comment]
Hello!
Thanks for the fast reply.

My deepstack is running on a seperate server. It is idle. I restarted it. It is not getting hit with requets.
The high cpu seems to be AITool.
![image](https://user-images.githubusercontent.com/4264240/158703299-5bbb2358-7ceb-4c86-acb7-9720264a4a13.png)
Memory is going between 150 and 300mb in a fast manner.

**Comment by VorlonCD** [comment]
Close AITOOL, backup the files and delete the AITOOL.DATABASE.* files.  This is the history database so you will loose the current history of course.

I supposed something could be corrupt in AITOOL.SETTINGS.JSON, but if you delete that you would have to reconfigure ALL settings.

**Comment by apedance** [comment]
Yeah, I can not get it do drop to normal idle %.
I deleted the database. Started with a clean database. Nothing worked.
Can't change any settings anymore - instantly crashes the app. Need to force quit it.
The version of the app does not matter. All versions have high cpu usage.
