### ISSUE TITLE
New Win11 Updates broke AITool

### ISSUE THREAD

**Issue by MnM001** [VorlonCD/bi-aidetection#321]
Have applied  the latest Windows 11 Updates:

- May 10, 2022—KB5013943 (OS Build 22000.675)

and

- May 10, 2022-KB5013628 Cumulative Update for .NET Framework 3.5 and 4.8 for Windows 11

Now AITool wont start anymore:

![image](https://user-images.githubusercontent.com/15014858/167966249-4f32e532-7ba8-4650-b0d6-c3eca6466d24.png)

BlueIris runs OK.

**Comment by VorlonCD** [comment]
Make sure using the latest:
https://github.com/VorlonCD/bi-aidetection/tree/master/src/UI/Installer

Does it happen if you rename "_SETTINGS" sub folder to settings.backup?    If that fixes, the config file was corrupt and you will need to re-configure your cameras.   Newer versions less likely to cause corrupt settings files.

I kind of doubt its directly due to an update since I've been on win11 for a while and keep up with the updates.

Perhaps test with antivirus disabled.

**Comment by MnM001** [comment]
Hi,

I can confirm that I am running the latest version.
I have tried the upgrade again. It is not the .NET that breaks it. It is the KB5013943 that breaks it.
I have installed AITool from scratch and got the same error.
Interestingly enough when I tried to run event viewer on the PC that didn't start also. So it looks like this update is corrupting a few things on my PC and might not be AITool related.
I will keep testing.
Thanks

**Comment by MnM001** [comment]
Yes looks like a Windows issue and not AITool issue.
Link below shows possible fix. Haven't tested it yet:

https://www.bleepingcomputer.com/news/microsoft/windows-11-kb5013943-update-causes-0xc0000135-application-errors/

**Comment by MnM001** [comment]
The fix in the article linked above worked.

Basically I applied all the updates and reboot PC.

I did not have .NET 3.5 installed so I went to:

Control Panel > Programs > Turn Windows features on or off and make sure .NET Framework 3.5 (includes .NET 2.0 and 3.0)

enabled the above, let it install then reboot PC.
Everything started working after that.
