### ISSUE TITLE
New image processing cooldown

### ISSUE THREAD

**Issue by Judman** [VorlonCD/bi-aidetection#35]
Hey! Love to tool and updated form Gentle Pumpkins 1.67 to this forks 1.77.

I have a question about image processing cooldowns. I have BI set to send an image once per second during a motion event, but AI tools seems to reject the subsequent images in the series because they fall within a "halfcool" timer. This is causing me to miss some motion events that were not missed with Gentle pumpkins 1.67 version.

Is there something I need to change so every image in the input folder is run through deepstack?

Logs here - https://pastebin.pl/view/644e3451

**Comment by VorlonCD** [comment]
You can actually set cooldown minutes to a decimal number.   Not entirely sure if 0 works but you can try.   Google "convert minutes to seconds" to find out the decimal number to enter.   Like .5 is 30 seconds and 0.166667 is 10 seconds.   I think I have mine set to .5

I dont think the original release actually reported when something was skipped due to halfcool, so you may have never known.  I could be wrong.  Its been known to happen. :)

**Comment by Judman** [comment]
Where is that setting?

I could be totally wrong about how previous versions worked.
In Gentle Pumpkins version, I believe they were getting processed by Deepstack because they would be in the history window and I wasn't missing as many alerts as I am since the upgrade. 

its like BI sees the start of the motion and begins sending the snapshot and AI Tools deems the event not interesting, even before the subject of the motion is visible enough to make a good call, then dismisses ever other snapshot in that motion event.

Before I thought it kept analyzing every image until it found a positive match, then it sent an alert and started the cooldown.

**Comment by VorlonCD** [comment]
Its the setting Cameras tab > Actions > Cooldown time.   If you set to 0.05 that means half a minute cooldown time.

**Comment by youzer-name** [comment]
VorlonCD I think there is a new issue with cooldown in version 1.67.8.21724 (9/20/2020 12:04:09 PM)

I am getting a cool down after the first image even though there was no detection. So it is only looking at the first image and then ignoring the following ones even though it hasn't detected anything. 

I rolled back to my local build which (1.67.8.26475 9/17/2020 2:42:31 PM) and it correctly processes all of the images until it gets a positive detection, then it goes into cooldown.

**Comment by VorlonCD** [comment]
@youzer-name - I havent made an official release for yet this since there are quite a few changes in it, but try the latest.   Make sure and backup your whole AITOOLS folder first.    A few major things, it uses an SQLITE db rather than the history.csv, and the history (and stats) now shows you any skipped images AND WHY.    Also, the cooldown setting used to be 'halved' in the code, but now it is the full value that you enter in cooldown for each camera.  (Before, 1 minute was actually .5 behind the scenes, not sure why)

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5283850/AITOOL-VORLONCD.zip)

If still acting weird with cooldown I'll need to see the log. (you can post DM to ipcamtalk if dont want to post publicly)

**Comment by VorlonCD** [comment]
Here is the update that appears to fix the cooldown issues:
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5284818/AITOOL-VORLONCD.zip)

**Comment by Judman** [comment]
Can confirm that the update provieded does fix the cooldown issue. Snapshots process as expected!

Thanks Vorlon!
