### ISSUE TITLE
Processing speed

### ISSUE THREAD

**Issue by Lazersfly** [VorlonCD/bi-aidetection#49]
The average time per image processed is 1100ms even though the deepstack instance is returning requests in 300ms, I do not know what is causing the slowdown but maybe processing multiple images at the same time would help. I am running the deepstack instance on a different machine so the issue may be uploading the image to that machine, but both machines are running via a gigabit connection. Any help with increasing the processing rate would be appreciated!

**Comment by Lazersfly** [comment]
It seems if I make more deepstack instances and add them I can increase processing speed, I do not know if this indicates a deepstack delay or a issue with AI-Tool.

**Comment by VorlonCD** [comment]
The additional time is due to 1) The time it takes to read the image file 2) The time it takes to submit the image to deepstack 3) the time it takes to run any triggers needed. and 4) potentially the time the image sits waiting in the queue if you dont dedicate enough deepstack workers.  The time you see in the deepstack window is JUST for its internal processing of the image.
