### ISSUE TITLE
[Feature request] integration with DOODS

### ISSUE THREAD

**Issue by 42ism** [VorlonCD/bi-aidetection#76]
Hi,

Do you think it might be possible to try replacing deepstackai with DOODS (Dedicated Open Object Detection Service) REST?
More information:
https://github.com/snowzach/doods

Thanks!

**Comment by Wumfie** [comment]
How does it compare to deepstack?

**Comment by 42ism** [comment]
I did not get a chance to compare it yet.

**Comment by VorlonCD** [comment]
I would like to try to add support for this and any others that make sense.   There is some framework I built in already in prep.

**Comment by VorlonCD** [comment]
@42ism @MYeager1967 -Try attached.  It has very preliminary DOODS support.   I have NOT had a chance to do other than very basic testing so far, but it does seem to work and spit out similar detection to deepstack.

Install one of the docker images here, or roll your own. (Be aware it is picky if you use a port other than 8080 - I tried 8084 first because 8080 was in use and the docker version still tried to use 8080 even though it was already in use)
https://github.com/snowzach/doods

Make sure its working by going to http://localhost:8080/version in a web browser first - you should see its version listed in a json string.

Then in AITTOOL, specify the ENTIRE URL for it to know it is a doods link:   http://localhost:8080/detect

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5513588/AITOOL-VORLONCD.zip)

**Comment by VorlonCD** [comment]
Let me know if DOODS AI server is any better at night (or day).   I've only been using it one night so far and there was nothing of interest anyway...

Note the History tab > Settings > Restrict threshold at source option.   When disabled, you will see a TON of detected objects at lower thresholds and it may help understand how it works better. 

1) Install docker if you dont have it

2) At a command prompt type **docker pull snowzach/doods:latest**

3) To run type **docker run --restart=always -it -p 8080:8080 snowzach/doods:latest**

Or as its instructions say, for Coral EdgeTPU: **docker run --restart=always -it --device /dev/bus/usb -p 8080:8080 snowzach/doods:latest**

It also has CUDA version but test normal version first.

4) Make sure its working by going to http://localhost:8080/version in a web browser first - you should see its version listed in a json string.

5) Then in AITTOOL, Settings tab specify the ENTIRE URL for it to know it is a doods link (Not just the IP/port!):
http://localhost:8080/detect

It must have "/detect"

Also, I tried to use it with a port other than 8080 because mine was in use but it didnt work, so I just disabled the program using that port and let it be default port for now. 

[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5524320/AITOOL-VORLONCD.zip)

**Comment by 42ism** [comment]
Thank you @VorlonCD I am trying build 2.0.134.7620 with DOODS right now. I will report back.

**Comment by Tinbum1** [comment]
I've been trying it out and I don't think it's quite as good a deepstack. The percentage accuracy is over quite a low range compared with deepstack which makes it harder to filter. 

First image is doods second is deepstack. (ditto stats).

![image](https://user-images.githubusercontent.com/66704787/99190756-5321cd80-2760-11eb-99eb-261538720afe.png)


![image](https://user-images.githubusercontent.com/66704787/99190771-63d24380-2760-11eb-8e2b-4d9c96d56b99.png)


![image](https://user-images.githubusercontent.com/66704787/99190839-d5aa8d00-2760-11eb-81a1-bc5dec8581d8.png)


![image](https://user-images.githubusercontent.com/66704787/99190823-ba3f8200-2760-11eb-9c13-e3c1d2c53a2c.png)

**Comment by 42ism** [comment]
This is also my first impression of running it for a couple of days and due to the low accuracy, it is harder to filter out false positives without risking detections. But it is still good to have options.

**Comment by VorlonCD** [comment]
It looks like you can give it other tflite or tensorflow models.  I wonder if they would work any better?   And apparently in order to use coral accelerator you have to modify the CONFIG.YAML file in the container, but I have no idea how to do yet. 
https://github.com/snowzach/doods

**Comment by MYeager1967** [comment]
Here's the config.yaml I used when I was using DOODS with HA. I had
downloaded the tensorflow model files and it was much better than the
tflite detection.

doods:
  detectors:
#    - name: default
#      type: tflite
#      modelFile: models/coco_ssd_mobilenet_v1_1.0_quant.tflite
#      labelFile: models/coco_labels0.txt
#      numThreads: 0
#      numConcurrent: 4
#      timeout: 2m
#    - name: edgetpu
#      type: tflite
#      modelFile:
models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
#      labelFile: models/coco_labels0.txt
#      numThreads: 0
#      numConcurrent: 4
#      hwAccel: true
    - name: default
      type: tensorflow
      modelFile: models/ssd_mobilenet_v1_coco_2018_01_28.pb # NAS
      #models/faster_rcnn_inception_v2_coco_2018_01_28.pb # Original
      labelFile: models/coco_labels1.txt
      width: 224
      height: 224
      numThreads: 4
      numConcurrent: 4

There is a trick that the - name has to match what it's looking for. There
may be a way to change it to look for tensorflow, but it was easier to just
change it to default in the config.

**Comment by VorlonCD** [comment]
@MYeager1967 - thanks!!    The question is still how to update the config file in the docker image.   This needs to be as easy as possible for folks that dont know Linux (I've only picked up a little over the years myself)

My Win10 box is using Docker with the new **WSL2** engine.   If I browse to **\\wsl$** in file explorer, I can browse/search files - I found the file but I'm not convinced I should just edit the file - path is weird, like its versioned or something:

"\\wsl$\docker-desktop-data\version-pack-data\community\docker\overlay2\fb618ec80446018c4dba947d445e9991a600df3eb947ff037dbfab9e59fade5e\diff\opt\doods\config.yaml"

I also tried the **Docker CP** command to try to copy the file from \opt\doods\config.yaml to my c: drive to edit, but I could never get the path correct.   

When I go into the docker **CLI** the file is /opt/doods/config.yaml but the CP command says that doesnt exist.

@snowzach -  Do you have any experience with doods docker image on Windows?   For deepstack docker image which this project uses also commonly changed parameters are changed with environment variables when you run the container:
https://deepstackcsharp.readthedocs.io/en/latest/objectdetection.html

I wonder if I'm missing something like that for Doods?   It would be really nice to have an easy way like that to modify detector settings.

**Comment by MYeager1967** [comment]
You don't. You create a volume outside the container for the config and model files. I'll post details tomorrow when I'm back on the computer...

**Comment by MYeager1967** [comment]
```sudo docker run -itd --name="DOODS" --restart=always --net=host -p 8080:8080 -e "TZ=America/New_York" -v /etc/localtime:/etc/localtime:ro -v /volume1/docker/doods/config.yaml:/opt/doods/config.yaml -v /volume1/docker/doods/models:/opt/doods/models myeager1967/doods-apollo-lake:latest```Is the command I used to start DOODS. The volume allows me to bring the configuration file and model files out of the container where I can modify them... You don't copy the files out to this volume, you create them there...
