### ISSUE TITLE
UNC is not retried when it goes away and comes back

### ISSUE THREAD

**Issue by weha** [VorlonCD/bi-aidetection#85]
I use a UNC path to monitor jpg files, the share went away for a few seconds (change in configuration) but the AI tool just stops monitoring the folder when it goes away and does not retry.
Maybe retry every n seconds? or n minute?

**Comment by VorlonCD** [comment]
Can you test this?   If there is an error with the connection it will keep retrying every 5 minutes (30000ms) as defined by **FileSystemWatcherRetryOnErrorTimeMS** setting in the JSON file.
[AITOOL-VORLONCD.zip](https://github.com/VorlonCD/bi-aidetection/files/5527506/AITOOL-VORLONCD.zip)

**Comment by weha** [comment]
Seems to work, but I lost my image masks now :(

**Comment by VorlonCD** [comment]
It should have tried to migrate any CAMERANAME.BMP files in the original AITOOL.EXE folder or CAMERAS folder over to the \_SETTINGS sub folder.   Did it miss one?  If so just drop the CAMERANAME.BMP in the new folder.

**Comment by weha** [comment]
It seems to have renamed the cameras for some reason?
I have my duplicate cameras starting with "ai" in the name, this has been removed, input file begins with has remained the same.

**Comment by VorlonCD** [comment]
Oh yes, if I see the cameraname starts with AI I remove it.   As far as I have seen AI should only be for the INPUT FILE BEGINS with.  I could certainly be wrong.

**Comment by weha** [comment]
Not sure why it has to be removed? It's just a name is it not? :)
It was not the case with the previous version so this is why it did not recognize the ainame.bmp files.

**Comment by VorlonCD** [comment]
I remember now why I automatically take out AI from the camera name.  ('Input file begins with' name is left alone)

When you use the "duplicate BI camera" method (which I think is now not the preferred method on the instructions for AITOOL first forum page), the **AI**CAMERA **_only_** job is to create new images.  But the main BI CAMERA is the one that we trigger to cause an alert to be recorded.   You can see how it wouldnt trigger the right camera if you had it set this way:

- AITOOL Camera name = AICAMERA
- BI Camera names = AICAMERA & CAMERA
- The trigger URL for BI has this VARIABLE in it:  **&camera=[camera]** - which is replaced with **AI**CAMERA rather than **CAMERA**   So, for folks using that variable, it wouldnt trigger the correct camera.   If you have the camera name hardcoded in the URL it would of course work.   But one goal is to be able to have the SAME URL for each camera so the setting can be cloned from one camera to the next.   With the latest version you can now use the same URL for every camera like this:

`[BlueIrisURL]/admin?trigger&camera=[camera]&user=[Username]&pw=[Password]&flagalert=1&memo=[summary]&jpeg=[ImagePathEscaped]`

So best to leave AI out of camera name unless I'm missing something.

**Comment by weha** [comment]
hmm ok, I did not know about the "new" method. 
I just checked but it seems that I'm missing some configuration steps that can't be performed because of only using one camera.

I see what you are getting at but you can't just assume the ainame is the same as the main camera name.
Unless you do a check if the camera exists with ai removed?
You could also provide an extra field to override the variable with the main camera so the name matches the actual camera being monitored but there are arguments for both methods really.
I just changed the variable in the link to a static name so this issue does not affect me.
