### ISSUE TITLE
Correctly monitor subfolders without hanging

### ISSUE THREAD

**Issue by MFornander** [VorlonCD/bi-aidetection#99]
Setup:
I'd like to leverage my Amcrest (Dahua based) IP-Cams motion sensors, have AI-Tool validate these snapshots, and then have AI-Tool trigger BlueIris to flag clips.  So instead of having BI provide the snapshots, I'd like the cams do that so leave BI to only record the streams.

Amcrest IPCams can save to a network path (NFS but that doesn't matter here) and the format is:
`{ROOT}/{date}/001/jpg/{hour}/{minute}/{second}[M][0@0][0].jpg`

Leaving "Input files begins with" blank and setting "Input Folder" to {ROOT} (Z:\b-trash for the b-trash camera) works if the images appear at {ROOT}.  If images appear in subfolders then AI-Tool hangs and no more images are processes until the program is restarted.  ImgQueued increments but no processing takes place.

Exact repro steps for bug:
1. Create a camera with "Name"='abc', "Input file begins with" set to empty, and "Input folder" set to 'C:\\' with "Monitor Subfolders" checked.
2. Copy a [picture named imageA.jpg into 'C:\\'   (root of camera)
3. See AI-Tool process that image and attribute it to 'abc' camera.
4. Create folder 'test' at 'C:\test'
5. Copy a picture imageB.jpg into 'C:\\test'
6. See AI-Tool's log failing to process image.
7. Copy a picture named imageC.jpg into root again that worked before.
8. Watch Ai-Tool still being hung and not process an image in a location that previously worked.
9. Restart AI-Tool to get processing working again.

**Comment by MFornander** [comment]
(related issue)
I will have all my cameras with empty "Input file begins with" prefix, but different "Input Folder" paths and names.  Will this work with the Default Camera code in GetCamera?  Looks like the first Camera with empty prefix becomes the default cam?

**Comment by VorlonCD** [comment]
Does it still happen if you compile the latest version yourself?   Lots of changes since the last official release posted.   I think some folder "exists" checking was moved to a background thread.

Also, all bets are off trying to monitor non windows OS file changes.   And if you have it set to looking for changes in any subfolders, for 1000's of files I imagine that would take a while.  My amcrest camera was painfully slow trying to browse the structure of its SD card so I gave up on that.  And I was even hard-wired to the device.

**Comment by MFornander** [comment]
On Linux right now and wanted to keep the BI machine pretty untainted.  Let me see if I can boot up a Win10 VM with VisualStudio and compile the latest version.

The file change watcher is working ok actually, but I may be getting a duoble event witch is fine.  The IPCam is writing using NFS to Synology but AI-Tool is getting the change trigger fine suing Samba on the same share.  I'll look at this later since it kworks fine.

**Comment by MFornander** [comment]
BTW just repoed using just a local drive as root, no shares, NFS, or samba,  Just D:\ with images copied into the D:\ Image Folder.  Same issue.

When a file is copied into a subfolder, there is the dogs and cats exception and no processing happens after that.  Have to restart to process anything else and the ImgQueue keeps growing even with images from working cams since the procesing loop  has stopped I guess.  I'll get back to this with the latest code after I get a windev machine up but I think there are at least three issues:

1. Subfolders as described above causes and exception in the image processing loop (GetCamera needs work).
2. There can be only one default cam even though multiple cams can have empty prefix and different search paths. (GetCamera needs work)
3. Whole tool stops processing images if there is an exception in the processing loop.

**Comment by MFornander** [comment]
(also you rock for making this!)

**Comment by VorlonCD** [comment]
just pushed an update that should make GetCamera work better.   Also, since the version you were last using I also added the ability to re-try the file watcher connection in the case of failure (like a server reboots, etc).

**Comment by doudar** [comment]
I went this route also, but ended up switching back to the cameras creating the alerts and BI generating the images. You can still keep "limit decoding" turned on and BI doesn't use noticeable processing power to generate the snapshots. Honestly, running the FTP server probably uses more CPU resources. 

Admittedly, It isn't as nice as just having the cameras directly generate the images (because of the extra non-flagged alerts) but I couldn't get a script to do directory cleanup as nicely as BI (which only deletes the files *it* generates).
